# Analyze the Political Orientation of Media Outlets in the Mediacloud Dataset

This notebook explores the **political orientation of news domains** using dataset that you can download [here (GitHub)](https://github.com/amirzon10/AI-Regulation-Discourse-in-News-A-Longitudinal-Study-Post-ChatGPT-2020-2025-/blob/main/data/mediacloud-2020-2025-dataset.csv). 

The orientations are categorized as:
- `lean-left`
- `left`
- `center`
- `lean-right`
- `right`

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

### Dataset Overview

We collected thousands of domains and mapped them to their political orientation.  
This helps us understand the distribution of media bias globally across different outlets.

In [ ]:
#load your dataset
df = pd.read_csv("data/mediacloud-2020-2025-dataset.csv")
df.head()

id  \
0  1dc171e7750c319dc4a7b4ca87c8a6f5587c0e9481f129...   
1  e6a47f0c7b6de768d799e603b5797ca432f9af6903de7b...   
2  8061d40a29f0fcf33e6906573a72389a4c0a0cc136522c...   
3  d411e1a49c87e2e710c054d514f58beebcfa2f275107d8...   
4  c8ce06691fdf797a875be76c82efb7b0fab0d3d62a795c...   

                       indexed_date language      media_name       media_url  \
0  2025-11-03 00:22:19.404264+00:00       en  techcrunch.com  techcrunch.com   
1  2025-11-02 23:17:22.553191+00:00       en    livemint.com    livemint.com   
2  2025-11-02 21:51:34.827292+00:00       en      apnews.com      apnews.com   
3  2025-11-02 20:26:57.088674+00:00       es    infolibre.es    infolibre.es   
4  2025-11-02 20:17:51.246694+00:00       en     thestar.com     thestar.com   

  publish_date                                              title  \
0   2025-11-02  Google pulls Gemma from AI Studio after Senato...   
1   2025-11-02  Here's why India’s AI content draft rules miss...   
2   2025-11-02  Who is Zico Kolter? A professor leads OpenAI s...   
3   2025-11-02  ChatGPT no es un psicólogo, pero cambiará su l...   
4   2025-11-02  Like maple syrup and hockey, AI must become a ...   

                                                 url  
0  https://techcrunch.com/2025/11/02/google-pulls...  
1  https://www.livemint.com/opinion/online-views/...  
2  https://apnews.com/article/openai-safety-chatg...  
3  https://www.infolibre.es/politica/chatgpt-rect...  
4  https://www.thestar.com/business/opinion/like-...

In [ ]:
#check the dataset size
df.shape

#check language distribution
language_size = df['language'].size
print(f"Total entries in language column: {language_size}")
language_counts = df['language'].value_counts()
print("Language distribution:")
print(language_counts)


Total entries in language column: 35399
Language distribution:
en    28928
de     1724
es      831
pl      807
it      631
fr      466
ja      368
zh      316
sv      284
nl      247
ro      209
pt      131
id       84
hr       43
fi       36
hu       36
no       33
tr       30
ru       29
sq       17
ko       16
hi       15
th       14
bg       12
el       11
ca       11
fa        9
tl        8
la        8
uk        7
cs        5
he        4
ar        4
gl        3
is        3
sr        3
mk        2
ur        2
se        2
sw        2
ta        1
sk        1
nn        1
nb        1
ml        1
ka        1
mt        1
az        1
Name: language, dtype: int64


In [ ]:
# !this will be edited!

#creating a simple bias mapping (will be expanded)
bias_map = {
    "theguardian.com": "left",
    "nytimes.com": "left",
    "cnn.com": "lean left",
    "bbc.co.uk": "center",
    "reuters.com": "center",
    "foxnews.com": "lean right",
    "wsj.com": "lean right",
    "breitbart.com": "right",
    "abcnews.go.com": "lean left",
    "alternet.org": "left",
    "apnews.com": "center",
    "yahoo.com": "lean left",
    "nbcnews.com": "lean left",
    "thehill.com": "center",
    "theepochtimes.com": "right",
    "seattletimes.com": "center",
    "forbes.com": "center",
    "thetimes.co.uk": "right",
    "msnbc.com": "left",
    "huffpost.com": "left",
    "vox.com": "left",
    "npr.org": "center",
    "usatoday.com": "center",
    "bloomberg.com": "center",
    "washingtonpost.com": "lean left",
    "nationalreview.com": "right",
    "dailycaller.com": "right",
    "newsmax.com": "right",
    "thefederalist.com": "right",
    "propublica.org": "lean left",
    "politico.com": "center",
    "axios.com": "center",
    "newyorker.com": "left",
    "motherjones.com": "left",
    "townhall.com": "right",
    "reason.com": "lean right",
    "slate.com": "left",
    "theatlantic.com": "lean left",
    "pjmedia.com": "right",
    "washingtontimes.com": "right",
    "thebulwark.com": "center",
    "justthenews.com": "right",
    "insider.com": "lean left",
    "cbsnews.com": "center",
    "dailymail.co.uk": "right",
    "marketwatch.com": "center",
    "businessinsider.com": "lean left",
    "buzzfeednews.com": "left",
    "fivethirtyeight.com": "center",
    "realclearpolitics.com": "center",
    "theintercept.com": "left",
    "truthout.org": "left",
    "spectator.org": "right",
    "americanthinker.com": "right",
    "dw.com": "center",
    "rte.ie": "center",
    "straitstimes.com": "center",
    "scmp.com": "center",
    "telegraph.co.uk": "lean right",
    "skynews.com.au": "lean right",
    "spectator.co.uk": "lean right",
    "nationalpost.com": "lean right",
    "jpost.com": "lean right",
    "rt.com": "right",
    "sputniknews.com": "right",
    "israelnationalnews.com": "right",
    "lemonde.fr": "left",
    "elperiodico.com": "left",
    "derfreitag.de": "left",
    "jacobinmag.com": "left",
    "ilmanifesto.it": "left",
    "cbc.ca": "lean left",
    "abc.net.au": "lean left",
    "globalnews.ca": "lean left",
    "theage.com.au": "lean left",
    "irishmirror.ie": "lean left",
    "stuff.co.nz": "lean left",
    "techcrunch.com": "center",
    "livemint.com": "center",
    "infolibre.es": "left",
    "bt.no": "center",
    "jang.com.pk": "lean right",
    "voc.com.cn": "right",
    "thestar.com": "lean left",
    "fortune.com": "center",
    "elplural.com": "left",
    "malaysianews.net": "center",
    "telegraphindia.com": "center",
    "marianne.net": "left",
    "newsday.com": "center",
    "financialexpress.com": "center",
    "globenewswire.com": "center",
    "ts.fi": "center",
    "kuna.net.kw": "right",
    "courrier-picard.fr": "center",
    "independent.co.uk": "lean left",       
    "rri.ro": "center",                     
    "inquirer.com": "lean left",            # US – Philadelphia Inquirer, historically liberal-leaning
    "metbuat.az": "center",                 # Azerbaijan – News aggregator, neutral tone
    "eldiario.com.ar": "left",              # Argentina – Progressive, investigative journalism
    "nuevodiarioweb.com.ar": "center",
    "gizmodo.jp": "center",                 # Japan – Tech-focused, generally neutral
    "malaymail.com": "center",             # Malaysia – Mainstream daily, moderate tone
    "winnipegfreepress.com": "lean left",  # Canada – Regional paper, socially liberal editorial stance
    "dubaichronicle.com": "center",        # UAE – Business and lifestyle, neutral tone
    "necocheanet.com.ar": "center",        # Argentina – Regional outlet, moderate reporting
    "nigerianpilot.news": "lean right",
    "levante-emv.com": "center",               # Spain – Regional daily, moderate tone
    "aa.com.tr": "right",                      # Turkey – State-run Anadolu Agency, pro-government
    "elperiodicomediterraneo.com": "center",  # Spain – Regional outlet, neutral reporting
    "channelnewsasia.com": "center",          # Singapore – Public broadcaster, factual and balanced
    "lavanguardia.com": "lean left",          # Spain – Mainstream daily, socially liberal editorial stance
    "gbnews.com": "right",                    # UK – Right-leaning, populist editorial tone
    "expansion.com": "center",                # Spain – Business-focused, neutral tone
    "tageszeitung.it": "left",                # Italy – Progressive, critical of establishment
    "pakistantoday.com.pk": "center",         # Pakistan – Balanced editorial tone
    "indiatimes.com": "center",
    "benzinga.com": "center",                  # Financial news, rated center by Ad Fontes Media
    "app.com.pk": "center",                   # Pakistan – Associated Press of Pakistan, state-run, neutral tone
    "techradar.com": "center",                # Tech-focused, rated center by Biasly
    "businesstimes.com.sg": "center",         # Singapore – Business daily, neutral editorial stance
    "krytykapolityczna.pl": "left",           # Poland – Progressive intellectual journal
    "today.az": "lean right",                 # Azerbaijan – Pro-government tone
    "codezine.jp": "center",                  # Japan – Tech and developer-focused, neutral content
    "sandiegouniontribune.com": "lean left",  # US – Rated lean left by AllSides
    "livescience.com": "center",              # Science journalism, rated center by AllSides
    "vice.com": "left",                       # Investigative and alternative journalism, rated left by AllSides
    "muvitv.com": "center",                   # No strong bias detected; neutral entertainment/news mix
    "cronista.com": "center",                 # Argentina – Business-focused, moderate tone
    "wellandtribune.ca": "center",            # Canada – Regional daily, neutral tone
    "niagarafallsreview.ca": "lean left",     # Canada – Rated lean left by Media Bias/Fact Check
    "thespec.com": "lean left",               # Canada – Hamilton Spectator, progressive editorial tone
    "cbj.ca": "center",                       # Canada – Canadian Business Journal, neutral reporting
    "therecord.com": "lean left",             # Canada – Waterloo Region Record, socially liberal tone
    "ocregister.com": "lean right",           # US – Orange County Register, rated lean right by AllSides
    "medianama.com": "lean left",             # India – Tech policy site, progressive/liberal editorial stance
    "syracuse.com": "center",
    "nyunews.com": "center",                # NYU student paper, neutral tone
    "okdiario.com": "right",                # Spain – Far-right, nationalist editorial stance
    "einpresswire.com": "center",           # Press release distributor, non-editorial
    "itweb.co.za": "center",                # South Africa – Tech/business, neutral tone
    "businessday.ng": "center",             # Nigeria – Business-focused, moderate tone
    "iafrica.com": "center",                # South Africa – Aggregator, neutral
    "diepresse.com": "center",              # Austria – Conservative-liberal, moderate tone
    "guardian.ng": "lean left",             # Nigeria – Progressive editorial stance
    "hindustantimes.com": "center",         # India – Rated center by AllSides and Biasly
    "contrepoints.org": "right",            # France – Libertarian, pro-market stance
    "thisdaylive.com": "center",            # Nigeria – Balanced reporting
    "ghanamma.com": "center",               # Ghana – Aggregator, neutral tone
    "newsghana.com.gh": "center",           # Ghana – National news, moderate tone
    "bursa.ro": "center",                   # Romania – Financial news, neutral
    "focus.de": "center",                   # Germany – Mainstream, moderate tone
    "ilsole24ore.com": "center",            # Italy – Business-focused, neutral
    "thebulletin.be": "center",             # Belgium – Expat-focused, neutral
    "wired.com": "left",                    # US – Rated left by AllSides and Ad Fontes
    "cnet.com": "center",                   # US – Tech reviews, rated center
    "heise.de": "center",                   # Germany – Tech-focused, neutral
    "theglobeandmail.com": "center",        # Canada – Rated center by AllSides and Ad Fontes
    "merca20.com": "center",                # Mexico – Marketing and business, neutral
    "arstechnica.com": "center",            # US – Tech and policy, rated center
    "hollywoodreporter.com": "center",      # US – Entertainment news, neutral
    "gizmodo.com": "lean left",             # US – Tech and culture, progressive tone
    "nation.com.pk": "lean right",          # Pakistan – Conservative editorial stance
    "thebftonline.com": "center",           # Ghana – Business and finance, neutral
    "telegraf.rs": "center",                # Serbia – Mainstream daily, moderate tone
    "dailycampus.com": "center",            # University of Connecticut student paper
    "dailytimes.com.pk": "center",          # Pakistan – Balanced reporting
    "thenationonlineng.net": "lean right",  # Nigeria – Conservative editorial stance
    "tasnimnews.com": "right",              # Iran – State-affiliated, conservative
    "standard.co.uk": "lean left",          # UK – Evening Standard, socially liberal
    "hsbnoticias.com": "center",            # Colombia – Regional outlet, neutral
    "diariodelsur.com.co": "center",        # Colombia – Regional daily, moderate tone
    "engadget.com": "center",               # Tech-focused, neutral tone
    "manilatimes.net": "lean right",        # Philippines – Conservative editorial stance
    "baltictimes.com": "center",            # Baltic region – English-language, neutral
    "sky.com": "center",                    # UK – Sky News, rated center by AllSides
    "zdnet.com": "center",                  # Tech-focused, neutral tone
    "rollingstone.com": "lean left",        # US – Progressive cultural coverage
    "vnanet.vn": "right",                   # Vietnam – State-run, pro-government
    "nypost.com": "lean right",             # US – Rated lean right by AllSides and Ad Fontes
    "news18.com": "center",                 # India – Mainstream, moderate tone
    "tengrinews.kz": "center",              # Kazakhstan – National news, neutral
    "columbiachronicle.com": "center",      # Columbia College Chicago student paper
    "thehindubusinessline.com": "center",   # India – Business-focused, neutral
    "latimes.com": "lean left", 
    "twincities.com": "center",              # US – St. Paul Pioneer Press, moderate tone
    "pilotonline.com": "center",             # US – Virginian-Pilot, neutral reporting
    "theverge.com": "lean left",             # US – Tech and culture, progressive tone
    "courant.com": "lean left",              # US – Hartford Courant, socially liberal
    "mashable.com": "lean left",             # US – Tech and entertainment, progressive tone
    "orlandosentinel.com": "center",         # US – Regional daily, moderate tone
    "sun-sentinel.com": "center",            # US – South Florida Sun Sentinel, neutral
    "cnbc.com": "center",                    # US – Business-focused, moderate tone
    "enca.com": "center",                    # South Africa – News channel, neutral tone
    "jpnn.com": "center",                    # Indonesia – Aggregator, neutral
    "indianexpress.com": "center",           # India – Balanced editorial stance
    "deccanchronicle.com": "center",         # India – Mainstream daily, moderate tone
    "thevanguardusa.com": "right",           # US – Conservative commentary
    "thewest.com.au": "center",              # Australia – Regional daily, neutral tone
    "prnewswire.com": "center",              # US – Press release distributor, non-editorial
    "bbc.com": "center",                     # UK – Public broadcaster, rated center
    "ibtimes.com": "center",                 # US – International Business Times, neutral
    "234radio.com": "center",                # Nigeria – Entertainment/news mix, neutral
    "legit.ng": "center",                    # Nigeria – Pop culture and news, neutral
    "rappler.com": "lean left",              # Philippines – Progressive, investigative
    "ibtimes.co.uk": "center",               # UK – Business and tech, neutral tone
    "observer.com": "lean left",             # US – Culture and politics, progressive
    "india.com": "center",                   # India – Aggregator, neutral tone
    "yaledailynews.com": "center",           # US – Student paper, balanced tone
    "businessinsider.jp": "center",          # Japan – Business-focused, neutral
    "prtimes.jp": "center",                  # Japan – Press release distributor
    "bicollegenews.com": "center",           # US – Student paper, neutral
    "bhaskar.com": "center",                 # India – Dainik Bhaskar, mainstream Hindi daily
    "udn.com": "center",                     # Taiwan – United Daily News, neutral
    "faz.net": "center",                     # Germany – Frankfurter Allgemeine Zeitung, moderate
    "newsweek.com": "center",                # US – Rated center by AllSides and Ad Fontes
    "theinfostride.com": "center",           # Nigeria – Tech and news aggregator
    "denverpost.com": "lean left",           # US – Rated lean left by AllSides
    "cityam.com": "lean right",              # UK – Business daily, pro-market stance
    "techcabal.com": "center",               # Nigeria – Tech-focused, neutral
    "aljazeera.com": "lean left",            # Qatar – Progressive international coverage
    "nation.africa": "center",               # Kenya – Nation Media Group, balanced tone
    "stol.it": "center",                     # Italy – South Tyrol outlet, neutral
    "ibtimes.co.in": "center",               # India – Business and tech, neutral
    "boomlive.in": "center",                 # India – Fact-checking site, neutral
    "freepressjournal.in": "lean left",      # India – Progressive editorial stance
    "bernama.com": "center",                 # Malaysia – State-run, factual tone
    "dailyfreepress.com": "center",          # US – Boston University student paper
    "theconversation.com": "center",         # Global – Academic commentary, neutral
    "nzherald.co.nz": "center",              # New Zealand – Mainstream daily, moderate tone
    "thefrontierpost.com": "center",         # Pakistan – Regional outlet, neutral
    "timesofmalta.com": "center",            # Malta – National daily, moderate tone
    "tribunnews.com": "center",              # Indonesia – Mainstream outlet, neutral
    "adnkronos.com": "center",               # Italy – News agency, neutral
    "collegian.com": "center",               # US – Colorado State University student paper
    "bangkokpost.com": "center",             # Thailand – National daily, moderate tone
    "thestreet.com": "center",               # US – Business-focused, rated center
    "ammonnews.net": "right",                # Jordan – Conservative editorial stance
    "epochtimes.de": "right",                # Germany – Branch of The Epoch Times, conservative
    "arkansasonline.com": "center",          # US – Arkansas Democrat-Gazette, moderate tone
    "bzi.ro": "center",                      # Romania – Aggregator, neutral
    "l-a.no": "center",                      # Norway – Local outlet, neutral
    "heraldscotland.com": "lean left",       # UK – Scottish Herald, progressive tone
    "abc.es": "right",                       # Spain – Conservative editorial stance
    "libertaddigital.com": "right",          # Spain – Libertarian, pro-market
    "malaya.com.ph": "center",              # Philippines – Business-focused, moderate
    "monitorulbt.ro": "center",              # Romania – Regional outlet, neutral
    "24-7pressrelease.com": "center",        # US – Press release distributor
    "breizh-info.com": "right",              # France – Nationalist, far-right tone
    "prnewswire.co.uk": "center",            # UK – Press release distributor
    "dailythepatriot.com": "lean right",     # Pakistan – Conservative editorial stance
    "medicinehatnews.com": "center",         # Canada – Regional daily, neutral
    "lethbridgeherald.com": "center",        # Canada – Regional daily, moderate tone
    "ansa.it": "center",                     # Italy – National news agency, neutral
    "nrc.nl": "center",                      # Netherlands – NRC Handelsblad, moderate tone
    "iltempo.it": "right",                   # Italy – Conservative, anti-communist roots
    "alleghenycampus.com": "center",         # US – Student paper, neutral
    "jsonline.com": "lean left",             # US – Milwaukee Journal Sentinel, progressive tone
    "geo.tv": "center",                      # Pakistan – Mainstream outlet, neutral
    "nationalobserver.com": "lean left",     # Canada – Investigative, progressive tone
    "ildenaro.it": "center",                 # Italy – Business-focused, neutral
    "kessbenonline.com": "center",           # Ghana – News and radio, neutral
    "sbs.com.au": "center",                  # Australia – Public broadcaster, balanced tone
    "bworldonline.com": "center",            # Philippines – Business-focused, neutral
    "thehindu.com": "center",                # India – National daily, moderate tone
    "rebelnews.com": "right",                # Canada – Far-right commentary
    "nannews.ng": "center",                  # Nigeria – News agency, neutral
    "kelownadailycourier.ca": "center",      # Canada – Regional daily, neutral
    "chicagomaroon.com": "center",           # US – University of Chicago student paper
    "newsx.com": "center",                   # India – News channel, neutral tone
    "pentictonherald.ca": "center",          # Canada – Regional outlet, moderate tone
    "vision1fm.com": "center",               # Ghana – Radio and news, neutral
    "bostonglobe.com": "lean left",          # US – Rated lean left by AllSides
    "stabroeknews.com": "center",            # Guyana – National daily, moderate tone
    "elpais.com": "lean left",               # Spain – Progressive editorial stance
    "postandcourier.com": "lean right",      # US – Rated lean right by AllSides
    "opisantacruz.com.ar": "center",         # Argentina – Regional outlet, neutral
    "3szek.ro": "center",                    # Romania – Hungarian-language outlet, neutral
    "tnp.sg": "center",                      # Singapore – The New Paper, tabloid-style, neutral
    "investigaction.net": "left",            # Belgium – Anti-imperialist, progressive tone
    "thequint.com": "lean left",             # India – Progressive digital outlet
    "metro.co.uk": "center",
    "time.com": "lean left",
    "standardmedia.co.ke": "center",
    "chiangraitimes.com": "center",
    "kurier.at": "center",
    "rp.pl": "center",
    "edestad.nl": "center",
    "parismatch.com": "center",
    "philstar.com": "center",
    "temple-news.com": "center",
    "badgerherald.com": "center",
    "dailyrecord.co.uk": "lean left",
    "tribuneonlineng.com": "center",
    "economicconfidential.com": "center",
    "irishexaminer.com": "center",
    "scoop.co.nz": "center",
    "yehey.com": "center",
    "boe.es": "center",
    "jagran.com": "center",
    "zerohedge.com": "right",
    "championnews.com.ng": "lean right",
    "opiniaoenoticia.com.br": "center",
    "hvg.hu": "center",
    "newsdiaryonline.com": "center",
    "urdupoint.com": "center",
    "elperiodicoextremadura.com": "center",
    "politicshome.com": "center",
    "theblaze.com": "right",
    "tvp.info": "right",
    "detik.com": "center",
    "ltn.com.tw": "center",
    "bohuslaningen.se": "center",
    "ziaruldeolt.ro": "center",
    "island.lk": "center",
    "repubblica.it": "lean left",
    "shqip.al": "center",
    "monitor.al": "center",
    "gazzettadelsud.it": "center",
    "timesofisrael.com": "center",
    "gds.ro": "center",
    "noticiasdenavarra.com": "center",
    "arynews.tv": "lean right",
    "ilfoglio.it": "center",
    "nationalnetworkonline.com": "center",
    "loyolaphoenix.com": "center",
    "thedaonline.com": "center",
    "ipanewspack.com": "center",
    "thehoya.com": "center",
    "ghanabusinessnews.com": "center",
    "dr1.com": "center",
    "premiumtimesng.com": "center",
    "dailycollegian.com": "center",
    "theithacan.org": "center",
    "kristianstadsbladet.se": "center",
    "nzz.ch": "center",
    "liwwadders.nl": "center",
    "nsk.se": "center",
    "radio.cz": "center",
    "pakistanpressfoundation.org": "center",
    "therakyatpost.com": "center",
    "dominicantoday.com": "center",
    "maszol.ro": "center",
    "monitorulcj.ro": "center",
    "dziennik.pl": "center",
    "von.gov.ng": "center",
    "dailypost.ng": "center",
    "pressetext.com": "center",
    "bta.bg": "center",
    "newsday.co.tt": "center",
    "blueprint.ng": "center",
    "journal.com.ph": "center",
    "elojodigital.com": "center",
    "theweek.in": "lean left",
    "jungefreiheit.de": "right",
    "icelandreview.com": "center",
    "citizen.co.za": "center",
    "elsaltodiario.com": "left",
    "latribune.fr": "center",
    "globo.com": "center",
    "taipeitimes.com": "center",
    "correiobraziliense.com.br": "center",
    "thedartmouth.com": "center",
    "terra.com.br": "center",
    "curier.ro": "center",
    "oann.com": "right",
    "theinsightnewsonline.com": "center",
    "ziarulargesul.ro": "center",
    "radiodon.com.ar": "center",
    "todaygh.com": "center",
    "baltimoresun.com": "lean left",
    "kyodo.co.jp": "center",
    "dnaindia.com": "center",
    "yle.fi": "center",
    "rollcall.com": "center",
    "pressat.co.uk": "center",
    "vanityfair.com": "lean left",
    "stltoday.com": "center",
    "krone.at": "right",
    "independent.ng": "center",
    "ascii.jp": "center",
    "thegatewaypundit.com": "right",
    "stern.de": "lean left",                # Germany – Mainstream magazine, socially liberal
    "mitti.se": "center",                   # Sweden – Local news, neutral
    "lopinion.fr": "center",                # France – Business/politics, moderate
    "gazetanord-vest.ro": "center",         # Romania – Regional, neutral
    "nachrichten.at": "center",             # Austria – Oberösterreichische Nachrichten, moderate
    "cash.ch": "center",                    # Switzerland – Business/finance, neutral
    "sn.at": "center",                      # Austria – Salzburger Nachrichten, moderate
    "tagesspiegel.de": "lean left",         # Germany – Progressive editorial stance
    "zeit.de": "lean left",                 # Germany – Die Zeit, socially liberal
    "swarajyamag.com": "right",             # India – Hindu nationalist, conservative
    "brandonsun.com": "center",             # Canada – Regional daily, neutral
    "crikey.com.au": "left",                # Australia – Investigative, progressive
    "mustangnews.net": "center",            # US – Student paper, neutral
    "nairametrics.com": "center",           # Nigeria – Business/finance, neutral
    "upi.com": "center",                    # US – United Press International, wire service
    "flathatnews.com": "center",            # US – William & Mary student paper
    "moroccoworldnews.com": "center",       # Morocco – English-language, moderate
    "dailytribune.com": "center",           # Philippines – Mainstream daily, neutral
    "africannewsagency.com": "center",      # South Africa – Wire service, neutral
    "brisbanetimes.com.au": "lean left",    # Australia – Fairfax Media, progressive
    "smh.com.au": "lean left",              # Australia – Sydney Morning Herald, progressive
    "thefinancialdaily.com": "center",      # Pakistan – Business daily, neutral
    "centralmaine.com": "center",           # US – Regional daily, neutral
    "planbnoticias.com.ar": "center",       # Argentina – Regional, neutral
    "derstandard.at": "lean left",          # Austria – Progressive editorial stance
    "diariotextual.com": "center",          # Argentina – Regional, neutral
    "scroll.in": "lean left",               # India – Progressive digital outlet
    "dnevnik.rs": "center",                 # Serbia – Mainstream, neutral
    "lefigaro.fr": "lean right",            # France – Conservative editorial stance
    "corriereirpinia.it": "center",         # Italy – Regional, neutral
    "newsmirrorng.com": "center",           # Nigeria – Neutral
    "excelsior.com.mx": "center",           # Mexico – Mainstream daily, moderate
    "avvir.no": "center",                   # Norway – Regional, neutral
    "antiguatribune.com": "center",         # Antigua – National daily, neutral
    "vikingfusion.com": "center",           # US – Student media, neutral
    "dailynorthwestern.com": "center",      # US – Northwestern Univ. student paper
    "metrotvonline.com": "center",          # Indonesia – Mainstream TV, neutral
    "bowdoinorient.com": "center",          # US – Student paper
    "svnews.ro": "center",                  # Romania – Regional, neutral
    "dailytrojan.com": "center",            # US – USC student paper
    "industriemagazin.at": "center",        # Austria – Business, neutral
    "20min.ch": "center",                   # Switzerland – Tabloid, neutral
    "capital.ro": "center",                 # Romania – Business, neutral
    "dutchnews.nl": "center",               # Netherlands – English-language, neutral
    "dagsavisen.no": "lean left",           # Norway – Progressive editorial stance
    "ekathimerini.com": "center",           # Greece – Mainstream daily, moderate
    "hotnews.ro": "center",                 # Romania – Online daily, neutral
    "tiempodesanjuan.com": "center",        # Argentina – Regional, neutral
    "utdailybeacon.com": "center",          # US – Univ. of Tennessee student paper
    "cursdeguvernare.ro": "center",         # Romania – Policy/finance, neutral
    "thewalrus.ca": "left",                 # Canada – Progressive magazine
    "michigandaily.com": "lean left",       # US – Univ. of Michigan student paper
    "coyotechronicle.net": "center",        # US – CSU San Bernardino student paper
    "index.hu": "lean left",                # Hungary – Progressive, critical of govt
    "newsone.com": "lean left",             # US – African-American focus, progressive
    "cna.com.tw": "center",                 # Taiwan – Central News Agency, neutral
    "irishtimes.com": "lean left",          # Ireland – Progressive editorial stance
    "mercurynews.com": "lean left",         # US – San Jose Mercury News, progressive
    "bfmtv.com": "center",                  # France – 24h news channel, neutral
    "japantoday.com": "center",             # Japan – English-language, neutral
    "elcorreo.com": "center",               # Spain – Regional daily, neutral
    "un.org": "center",                     # UN News, neutral
    "mynavi.jp": "center",                  # Japan – Business/careers, neutral
    "tribune.net.ph": "center",             # Philippines – Mainstream daily
    "kenyanews.go.ke": "center",            # Kenya – State-run, neutral
    "diariosigloxxi.com": "center",         # Spain – Online daily, neutral
    "spotlightnepal.com": "center",         # Nepal – Independent, neutral
    "ansarpress.com": "lean right",         # Afghanistan – Conservative tone
    "co.za": "center",                      # South Africa – Generic domain aggregator
    "icirnigeria.org": "center",            # Nigeria – Investigative journalism, neutral
    "gazetadecluj.ro": "center",            # Romania – Investigative, neutral
    "thesandb.com": "center",               # US – Grinnell College student paper
    "lavozdegalicia.es": "center",          # Spain – Regional daily, neutral
    "vastranyland.fi": "center",            # Finland – Swedish-language, neutral
    "onet.pl": "center",                    # Poland – Mainstream portal, neutral
    "rawstory.com": "left",                 # US – Progressive commentary
    "dn.se": "center",                      # Sweden – Dagens Nyheter, moderate
    "thenews.com.pk": "center",             # Pakistan – Mainstream daily
    "svd.se": "lean right",                 # Sweden – Svenska Dagbladet, conservative
    "billboard.com": "center",              # US – Entertainment, neutral
    "welt.de": "lean right",                # Germany – Conservative editorial stance
    "di.se": "center",                      # Sweden – Business daily, neutral
    "dawn.com": "center",                   # Pakistan – Mainstream, neutral
    "gazetaprawna.pl": "center",            # Poland – Business/legal, neutral
    "schwartzreport.net": "left",           # US – Progressive commentary
    "theonlineclarion.com": "center",       # US – Madison College student paper
    "vrt.be": "center",                     # Belgium – Public broadcaster
    "sdpnoticias.com": "center",            # Mexico – Online news, neutral
    "tvn24.pl": "center",                   # Poland – 24h news channel, neutral
    "pakobserver.net": "lean right",        # Pakistan – Conservative editorial stance
    "thelocal.it": "center",                # Italy – English-language, neutral
    "srf.ch": "center",                     # Switzerland – Public broadcaster
    "kbs.co.kr": "center",                  # South Korea – Public broadcaster
    "nbcsvg.com": "center",                 # St. Vincent – National broadcaster
    "brecorder.com": "center",              # Pakistan – Business Recorder, neutral
    "khaama.com": "center",                 # Afghanistan – Neutral
    "taz.de": "left",                       # Germany – Die Tageszeitung, progressive
    "wnd.com": "right",                     # US – Far-right commentary
    "mirror.co.uk": "lean left",            # UK – Tabloid, socially liberal
    "knack.be": "lean left",              # Belgium – Investigative magazine, progressive
    "timeslive.co.za": "center",             # South Africa – Mainstream daily, neutral
    "jamaica-gleaner.com": "center",         # Jamaica – Rated center by Biasly
    "laverita.info": "right",                # Italy – Populist, conservative
    "mid-day.com": "center",                 # India – Tabloid, neutral
    "royalgazette.com": "center",            # Bermuda – National daily, moderate
    "affaritaliani.it": "center",            # Italy – Online daily, neutral
    "investors.com": "lean right",           # US – Investor’s Business Daily, pro-market
    "mediaindonesia.com": "center",          # Indonesia – Mainstream daily, neutral
    "iwnsvg.com": "center",                  # St. Vincent – Local news, neutral
    "orf.at": "center",                      # Austria – Public broadcaster
    "vol.at": "center",                      # Austria – Regional Vorarlberg outlet
    "thebridge.jp": "center",                # Japan – Business/tech, neutral
    "independent.ie": "center",              # Ireland – Irish Independent, moderate
    "ilmessaggero.it": "center",             # Italy – Mainstream daily, neutral
    "thenation.com": "left",                 # US – Progressive magazine
    "lasicilia.it": "center",                # Italy – Regional daily
    "wfuogb.com": "center",                  # US – Wake Forest student paper
    "albeu.com": "center",                   # Albania – News portal, neutral
    "timesindonesia.co.id": "center",        # Indonesia – Regional daily
    "panorama.com.al": "center",             # Albania – Mainstream daily
    "azcentral.com": "lean left",            # US – Arizona Republic, rated lean left
    "hongkongfp.com": "center",              # Hong Kong – Rated neutral by Ad Fontes
    "challenges.fr": "center",               # France – Business magazine
    "katadata.co.id": "center",              # Indonesia – Business/finance
    "24.kg": "center",                       # Kyrgyzstan – Neutral
    "newstalkzb.co.nz": "lean right",        # New Zealand – Talk radio, conservative
    "elmundo.es": "lean right",              # Spain – Conservative editorial stance
    "cincinnati.com": "center",              # US – Gannett/USA Today Network
    "newsroom.co.nz": "lean left",           # New Zealand – Progressive digital outlet
    "newcastillian.com": "center",           # Regional/local, neutral
    "dailyegyptian.com": "center",           # US – Southern Illinois Univ. student paper
    "melillahoy.es": "center",               # Spain – Regional daily
    "newindianexpress.com": "center",        # India – Mainstream daily
    "thenews-chronicle.com": "center",       # Nigeria – Neutral
    "elfinanciero.com.mx": "center",         # Mexico – Business daily
    "leadership.ng": "lean right",           # Nigeria – Conservative editorial stance
    "cmcforum.com": "center",                # US – Claremont McKenna student paper
    "searchlight.vc": "center",              # St. Vincent – National daily
    "newsweek.pl": "center",                 # Poland – Neutral
    "case.edu": "center",                    # US – University outlet
    "browndailyherald.com": "lean left",     # US – Brown Univ. student paper
    "uol.com.br": "center",                  # Brazil – Mainstream portal
    "thesewaneepurple.org": "center",        # US – Univ. of the South student paper
    "cronicadecantabria.com": "center",      # Spain – Regional daily
    "theeagleonline.com.ng": "center",       # Nigeria – Neutral
    "telegraaf.nl": "lean right",            # Netherlands – Conservative tabloid
    "adevarul.ro": "center",                 # Romania – Mainstream daily
    "meredithherald.com": "center",          # US – Meredith College student paper
    "dailytrust.com": "center",              # Nigeria – Mainstream daily
    "mediafax.ro": "center",                 # Romania – News agency
    "assamtribune.com": "center",            # India – Regional daily
    "paisano-online.com": "center",          # US – Univ. of Texas San Antonio student paper
    "variety.com": "center",                 # US – Entertainment, neutral
    "khybernews.tv": "center",               # Pakistan – Regional TV
    "calvinchimes.org": "center",            # US – Calvin Univ. student paper
    "ncregister.com": "right",               # US – Catholic Register, conservative
    "tn.com.ar": "center",                   # Argentina – Clarín Group, moderate
    "onlineindiannews.com": "center",        # India – Neutral
    "lexpress.fr": "lean left",              # France – Progressive editorial stance
    "cherokeephoenix.org": "center",         # US – Native American outlet
    "blic.rs": "center",                     # Serbia – Mainstream daily
    "manchestereveningnews.co.uk": "center", # UK – Rated center by Ground News
    "elperiodico.cat": "lean left",          # Spain – Catalan daily
    "ilgiorno.it": "center",                 # Italy – Regional daily
    "dunya.com": "lean right",               # Pakistan – Conservative
    "chroniclelive.co.uk": "center",         # UK – Regional daily
    "dailysabah.com": "lean right",          # Turkey – Pro-government
    "dailyillini.com": "center",             # US – Univ. of Illinois student paper
    "ondacero.es": "center",                 # Spain – National radio
    "dailynigerian.com": "center",           # Nigeria – Neutral
    "channelstv.com": "center",              # Nigeria – National broadcaster
    "promptnewsonline.com": "center",        # Nigeria – Neutral
    "realnewsmagazine.net": "center",        # Nigeria – Neutral
    "dailysignal.com": "right",              # US – Heritage Foundation, conservative
    "eltiempo.com": "lean left",             # Colombia – Progressive editorial stance
    "expansion.mx": "center",                # Mexico – Business daily
    "newtelegraphng.com": "center",          # Nigeria – Neutral
    "nos.nl": "center",                      # Netherlands – Public broadcaster
    "thepacer.net": "center",                # US – Univ. of Tennessee Martin student paper
    "inquisitr.com": "center",               # US – Entertainment/aggregator
    "antena3.com": "center",                 # Spain – Mainstream TV
    "thechronicle.com.gh": "center",         # Ghana – National daily
    "thedailybeast.com": "lean left",        # US – Progressive commentary
    "ziuadevest.ro": "center",               # Romania – Regional daily
    "buvoice.com": "center",                 # US – Baylor Univ. student paper
    "bzc.ro": "center",                      # Romania – Regional daily
    "sundayexpress.co.ls": "center",         # Lesotho – National daily
    "radaronline.com": "center",             # US – Celebrity/entertainment
    "africachinapresscentre.org": "center",  # Nigeria – Neutral
    "handelszeitung.ch": "center",           # Switzerland – Business daily
    "southafricatoday.net": "lean right",    # South Africa – Conservative tone
    "rnz.co.nz": "center",                   # New Zealand – Public broadcaster
    "aol.com": "center",                     # US – Aggregator
    "nzcity.co.nz": "center",                # New Zealand – Aggregator
    "parkiet.com": "center",                 # Poland – Business daily
    "berkshireeagle.com": "center",          # US – Regional daily
    "n-tv.de": "center",                     # Germany – Mainstream TV
    "nigeriagalleria.com": "center",         # Nigeria – Aggregator
    "brazzil.com": "center",                 # Brazil – Culture/news, neutral
    "rutlandherald.com": "center",          # US – Regional daily
    "thebatt.com": "center",                # Texas A&M student paper
    "mlive.com": "center",                  # Michigan local news, rated center
    "occidente.co": "center",               # Colombia – Regional, neutral
    "nigerianeye.com": "center",            # Nigeria – Aggregator, neutral
    "kohajone.com": "center",               # Albania – Mainstream daily
    "newsinvestigatorsng.com": "center",    # Nigeria – Investigative, neutral
    "diariopanorama.com": "center",         # Venezuela – Regional daily
    "internazionale.it": "lean left",       # Italy – Progressive, global focus
    "sicilianews24.it": "center",           # Italy – Regional daily
    "hola.com": "center",                   # Spain – Celebrity/entertainment
    "freep.com": "lean left",               # Detroit Free Press, progressive
    "foxbusiness.com": "lean right",        # US – Business, conservative tone
    "georgeherald.com": "center",           # South Africa – Regional daily
    "lanacion.com.ar": "lean right",        # Argentina – Conservative editorial stance
    "newslaundry.com": "lean left",         # India – Media watchdog, progressive
    "aajtak.in": "center",                  # India – Mainstream Hindi TV
    "independentaustralia.net": "lean left",# Australia – Progressive commentary
    "dailytitan.com": "center",             # CSU Fullerton student paper
    "euroweeklynews.com": "center",         # Spain – English-language expat news
    "dailystar.co.uk": "lean right",        # UK – Tabloid, conservative tone
    "elpueblodeceuta.es": "center",         # Spain – Regional daily
    "guyanachronicle.com": "lean right",    # Guyana – State-aligned, conservative
    "namibian.com.na": "center",            # Namibia – Independent daily
    "lusakatimes.com": "center",            # Zambia – Aggregator, neutral
    "curierulnational.ro": "center",        # Romania – National daily
    "romanialibera.ro": "lean right",       # Romania – Conservative editorial stance
    "rg.ru": "right",                       # Russia – Rossiyskaya Gazeta, state-run
    "rhythm937.com": "center",              # Nigeria – Radio, neutral
    "rnd.de": "center",                     # Germany – Regional daily
    "walesonline.co.uk": "center",          # UK – Regional daily
    "thaiexaminer.com": "center",           # Thailand – English-language, neutral
    "staradvertiser.com": "center",         # Hawaii – Honolulu Star-Advertiser
    "diariodenavarra.es": "center",         # Spain – Regional daily
    "bubblear.com": "center",               # Argentina – Entertainment/culture
    "czechjournal.cz": "center",            # Czech Republic – English-language
    "grist.org": "lean left",               # US – Environmental journalism
    "9news.com.au": "center",               # Australia – Mainstream TV
    "punto.com.ph": "center",               # Philippines – Regional daily
    "csmonitor.com": "lean left",           # Christian Science Monitor, progressive
    "levif.be": "center",                   # Belgium – Le Vif/L’Express, moderate
    "novinite.com": "center",               # Bulgaria – English-language, neutral
    "hurriyet.com.tr": "lean right",        # Turkey – Mainstream, pro-gov’t
    "chicagotribune.com": "lean right",     # US – Rated lean right by AllSides
    "sabah.com.tr": "right",                # Turkey – Pro-government
    "adaderana.lk": "center",               # Sri Lanka – Mainstream TV
    "globes.co.il": "center",               # Israel – Business daily
    "spiegel.de": "lean left",              # Germany – Der Spiegel, progressive
    "manager-magazin.de": "center",         # Germany – Business magazine
    "vetlandaposten.se": "center",          # Sweden – Regional daily
    "uiargonaut.com": "center",             # Univ. of Idaho student paper
    "theborneopost.com": "center",          # Malaysia – Regional daily
    "rediff.com": "center",                 # India – News portal
    "scientificamerican.com": "lean left",  # US – Science magazine, progressive
    "dispatch.com": "center",               # US – Columbus Dispatch
    "pbs.org": "lean left",                 # US – Public Broadcasting Service
    "nepalnews.com": "center",              # Nepal – Aggregator
    "mercado.com.ar": "center",             # Argentina – Business
    "ovaciones.com": "center",              # Mexico – Sports/politics, neutral
    "europapress.es": "center",             # Spain – News agency
    "cope.es": "lean right",                # Spain – Catholic/conservative radio
    "valenciaplaza.com": "center",          # Spain – Regional daily
    "stanforddaily.com": "center",          # Stanford Univ. student paper
    "sobifm.com": "center",                 # Nigeria – Radio
    "elperiodicodeportivo.com.co": "center",# Colombia – Sports
    "popmatters.com": "lean left",          # US – Cultural commentary
    "lavozdeasturias.es": "center",         # Spain – Regional daily
    "dailycal.org": "lean left",            # UC Berkeley student paper
    "standaard.be": "lean left",            # Belgium – De Standaard, progressive
    "ilmattino.it": "center",               # Italy – Regional daily
    "ksl.com": "center",                    # US – Utah-based, neutral
    "wpolityce.pl": "right",                # Poland – Conservative
    "oe24.at": "lean right",                # Austria – Tabloid, conservative
    "deutschlandfunk.de": "center",         # Germany – Public broadcaster
    "charter97.org": "lean left",           # Belarus – Opposition outlet
    "tt.com": "center",                     # Austria – Tiroler Tageszeitung
    "interia.pl": "center",                 # Poland – Mainstream portal
    "famagusta-gazette.com": "center",      # Cyprus – English-language
    "panorama.it": "center",                # Italy – Weekly magazine
    "emirates247.com": "center",            # UAE – Business/lifestyle
    "mxmindia.com": "center",               # India – Media/marketing
    "nationalenquirer.com": "right",        # US – Tabloid, sensationalist
    "affarsvarlden.se": "center",           # Sweden – Business
    "t-online.de": "center",                # Germany – Mainstream portal
    "talkingpointsmemo.com": "lean left",   # US – Progressive commentary
    "thecitizen.co.tz": "center",           # Tanzania – National daily
    "politicsweb.co.za": "center",          # South Africa – Commentary
    "thisisradionow.com": "center",         # Nigeria – Radio
    "uzone.id": "center",                   # Indonesia – Tech/entertainment
    "pagina12.com.ar": "left",              # Argentina – Progressive daily
    "ieyenews.com": "center",               # Cayman Islands – Local news
    "rosario3.com": "center",               # Argentina – Regional daily
    "egyptindependent.com": "center",       # Egypt – English-language
    "elciudadanoweb.com": "center",         # Argentina – Regional daily
    "nltimes.nl": "center",                 # Netherlands – English-language
    "lejdd.fr": "lean right",               # France – Journal du Dimanche
    "inquirer.net": "lean left",            # Philippines – Philippine Daily Inquirer
    "ew.com": "center",                     # US – Entertainment Weekly
    "nikkei.com": "center",                 # Japan – Business daily
    "mainichi.jp": "lean left",             # Japan – Progressive editorial stance
    "laopinioncoruna.es": "center",         # Spain – Regional daily
    "prospect.org": "left",                  # The American Prospect – progressive
    "thepostmillennial.com": "right",        # Canada – conservative, populist
    "thinkit.co.jp": "center",               # Japan – tech/business, neutral
    "ceskenoviny.cz": "center",              # Czech Republic – CTK news agency
    "sport.es": "center",                    # Spain – sports daily
    "laopiniondemalaga.es": "center",        # Spain – regional daily
    "lne.es": "center",                      # Spain – La Nueva España, regional
    "farodevigo.es": "center",               # Spain – regional daily
    "laopiniondemurcia.es": "center",        # Spain – regional daily
    "diariodeibiza.es": "center",            # Spain – regional daily
    "diariocordoba.com": "center",           # Spain – Córdoba daily
    "elperiodicodearagon.com": "center",     # Spain – regional daily
    "laopiniondezamora.es": "center",        # Spain – regional daily
    "diariodemallorca.es": "center",         # Spain – regional daily
    "eldia.es": "center",                    # Spain – Tenerife daily
    "foothillscript.com": "center",          # US – student paper
    "gazetadopovo.com.br": "right",          # Brazil – conservative editorial stance
    "rtl.de": "center",                      # Germany – mainstream TV
    "ajc.com": "lean left",                  # Atlanta Journal-Constitution
    "ilfattoquotidiano.it": "lean left",     # Italy – progressive, anti-establishment
    "bild.de": "lean right",                 # Germany – populist tabloid
    "ft.com": "center",                      # Financial Times – pro-market, centrist
    "rpereznetonline.com.ar": "center",      # Argentina – regional
    "lindependant.fr": "center",             # France – regional daily
    "cambodgemag.com": "center",             # Cambodia – English-language
    "kurir.rs": "lean right",                # Serbia – populist tabloid
    "midilibre.fr": "center",                # France – regional daily
    "prensaeconomica.com.ar": "center",      # Argentina – business
    "mediaset.it": "center",                 # Italy – mainstream TV
    "jurnalul.ro": "lean left",              # Romania – progressive
    "express.co.uk": "lean right",           # UK – Daily Express
    "stirileprotv.ro": "center",             # Romania – mainstream TV
    "rtl.nl": "center",                      # Netherlands – mainstream TV
    "politika.rs": "lean right",             # Serbia – conservative daily
    "nieuwsblad.be": "center",               # Belgium – mainstream daily
    "bazonline.ch": "center",                # Switzerland – Basler Zeitung
    "derbund.ch": "center",                  # Switzerland – Bern daily
    "bernerzeitung.ch": "center",            # Switzerland – Bern daily
    "tagesanzeiger.ch": "lean left",         # Switzerland – Zurich daily
    "okezone.com": "center",                 # Indonesia – mainstream portal
    "thediplomat.ro": "center",              # Romania – business/policy
    "cartacapital.com.br": "left",           # Brazil – progressive magazine
    "theweek.com": "center",                 # US – centrist magazine
    "ripplesnigeria.com": "center",          # Nigeria – neutral
    "rthk.hk": "center",                     # Hong Kong – public broadcaster
    "cnc3.co.tt": "center",                  # Trinidad – mainstream TV
    "redstate.com": "right",                 # US – conservative commentary
    "magic828.co.za": "center",              # South Africa – radio
    "rp-online.de": "center",                # Germany – Rheinische Post
    "beleggersbelangen.nl": "center",        # Netherlands – finance
    "sundiatapost.com": "center",            # Nigeria – neutral
    "orientalnewsng.com": "center",          # Nigeria – neutral
    "ilsecoloxix.it": "center",              # Italy – Genoa daily
    "larena.it": "center",                   # Italy – Verona daily
    "huelvainformacion.es": "center",        # Spain – regional daily
    "clubic.com": "center",                  # France – tech
    "europasur.es": "center",                # Spain – regional daily
    "diariodecadiz.es": "center",            # Spain – regional daily
    "diariodejerez.es": "center",            # Spain – regional daily
    "granadahoy.com": "center",              # Spain – regional daily
    "malagahoy.es": "center",                # Spain – regional daily
    "diariodesevilla.es": "center",          # Spain – regional daily
    "eldiadecordoba.es": "center",           # Spain – regional daily
    "diariodealmeria.es": "center",          # Spain – regional daily
    "science-et-vie.com": "center",          # France – science magazine
    "phonemantra.com": "center",             # India – tech
    "ksusentinel.com": "center",             # US – student paper
    "gazettenet.com": "center",              # US – regional daily
    "teletica.com": "center",                # Costa Rica – mainstream TV
    "ebc.com.br": "center",                  # Brazil – public broadcaster
    "istoe.com.br": "lean left",             # Brazil – progressive magazine
    "istoedinheiro.com.br": "center",        # Brazil – business
    "laprensalibre.cr": "center",            # Costa Rica – mainstream daily
    "bota.al": "center",                     # Albania – news portal
    "cotidianul.ro": "lean right",           # Romania – conservative
    "elconfidencial.com": "center",          # Spain – investigative, centrist
    "lavoz.com.ar": "center",                # Argentina – mainstream daily
    "ilgazzettino.it": "center",             # Italy – regional daily
    "startribune.com": "lean left",          # US – Minneapolis Star Tribune
    "sierraleonepress.com": "center",        # Sierra Leone – neutral
    "castellonplaza.com": "center",          # Spain – regional daily
    "authorityngr.com": "center",            # Nigeria – neutral
    "pointblanknews.com": "center",          # Nigeria – neutral
    "theroot.com": "left",                   # US – African-American progressive
    "thewrap.com": "center",                 # US – entertainment
    "gmanetwork.com": "center",              # Philippines – mainstream TV
    "thetrentonline.com": "center",          # Nigeria – commentary
    "aftonbladet.se": "lean left",           # Sweden – tabloid, progressive
    "hurriyetdailynews.com": "center",       # Turkey – English-language
    "buzzfeed.com": "lean left",             # US – progressive digital
    "politicalwire.com": "lean left",        # US – commentary
    "agi.it": "center",                      # Italy – news agency
    "larazon.es": "lean right",              # Spain – conservative daily
    "dailyguidenetwork.com": "lean right",   # Ghana – conservative
    "filmfare.com": "center",                # India – entertainment
    "thegazette.news": "center",             # Botswana – neutral
    "infosanpedro.com.ar": "center",         # Argentina – regional
    "limite42.com": "center",                # Argentina – regional
    "santafederf.com.ar": "center",          # Argentina – regional
    "fmcompromiso.com.ar": "center",          # Argentina – regional
    "radioaoran.com.ar": "center",              # Argentina – Regional outlet
    "reflejojujuy.com": "center",               # Argentina – Regional outlet
    "elnuevodia.com": "lean left",              # Puerto Rico – Progressive editorial stance
    "usmagazine.com": "center",                 # US – Entertainment, neutral
    "goo.ne.jp": "center",                      # Japan – Portal, neutral
    "axcessnews.com": "center",                 # US – Aggregator, neutral
    "ilgiornale.it": "lean right",              # Italy – Conservative daily
    "dubawa.org": "center",                     # Nigeria – Fact-checking, neutral
    "worldtribune.com": "right",                # US – Conservative commentary
    "alicanteplaza.es": "center",               # Spain – Regional daily
    "tampabay.com": "lean left",                # US – Tampa Bay Times, progressive
    "entornourgente.com": "center",             # Argentina – Regional outlet
    "nationaldailyng.com": "center",            # Nigeria – Neutral
    "thenewcrusadingguideonline.com": "center", # Ghana – Neutral
    "qz.com": "lean left",                      # US – Quartz, progressive business
    "newstatesman.com": "left",                 # UK – Progressive magazine
    "huntnewsnu.com": "center",                 # US – Northeastern Univ. student paper
    "newsblaze.com": "right",                   # US – Conservative commentary
    "salon.com": "left",                        # US – Progressive commentary
    "eleconomista.com.mx": "center",            # Mexico – Business daily
    "letelegramme.fr": "center",                # France – Regional daily
    "kosmo.com.my": "center",                   # Malaysia – Mainstream daily
    "newsbomb.gr": "lean right",                # Greece – Conservative tabloid
    "wired868.com": "center",                   # Trinidad – Sports/news
    "clarin.com": "lean right",                 # Argentina – Conservative daily
    "diariovasco.com": "center",                # Spain – Regional daily
    "stluciatimes.com": "center",               # St. Lucia – Neutral
    "ideal.es": "center",                       # Spain – Regional daily
    "agora-web.jp": "center",                   # Japan – Business/tech
    "catalunyapress.cat": "center",             # Spain – Regional outlet
    "jis.gov.jm": "center",                     # Jamaica – Government portal
    "mingpao.com": "center",                    # Hong Kong – Mainstream daily
    "naijafeed.com": "center",                  # Nigeria – Aggregator
    "ukrinform.ua": "center",                   # Ukraine – State news agency
    "newmail-ng.com": "center",                 # Nigeria – Neutral
    "politicsnigeria.com": "center",            # Nigeria – Neutral
    "gistmania.com": "center",                  # Nigeria – Entertainment/news
    "augustachronicle.com": "lean right",       # US – Regional daily
    "fakt.pl": "lean right",                    # Poland – Tabloid
    "polygon.com": "lean left",                 # US – Gaming/culture
    "sttinfo.fi": "center",                     # Finland – Press release distributor
    "persecondnews.com": "center",              # Nigeria – Neutral
    "ozgurkocaeli.com.tr": "center",            # Turkey – Regional daily
    "irna.ir": "right",                         # Iran – State-run
    "eiga.com": "center",                       # Japan – Entertainment
    "antiguaobserver.com": "center",            # Antigua – National daily
    "indystar.com": "lean left",                # US – Indianapolis Star
    "recorder.com": "center",                   # US – Regional daily
    "renasterea.ro": "center",                  # Romania – Regional daily
    "ilna.ir": "lean left",                     # Iran – Reformist outlet
    "opinione.it": "lean right",                # Italy – Conservative commentary
    "abstvradio.com": "center",                 # Antigua/Barbuda – Radio
    "gov.ky": "center",                         # Cayman Islands – Government portal
    "diariodeferrol.com": "center",             # Spain – Regional daily
    "diariodearousa.com": "center",             # Spain – Regional daily
    "economist.com": "center",                  # UK – The Economist, pro-market centrist
    "kauppalehti.fi": "center",                 # Finland – Business daily
    "barbadosgazette.com": "center",            # Barbados – Neutral
    "nationnews.com": "center",                 # Barbados – Mainstream daily
    "moss-dagblad.no": "center",                # Norway – Regional daily
    "cleveland.com": "center",                  # US – Cleveland Plain Dealer
    "newsonjapan.com": "center",                # Japan – Aggregator
    "gigazine.net": "center",                   # Japan – Tech/culture
    "ig.com.br": "center",                      # Brazil – Portal
    "tygodnikpowszechny.pl": "lean left",       # Poland – Catholic progressive weekly
    "newuniversity.org": "center",              # US – UC Irvine student paper
    "insider.co.uk": "center",                  # UK – Business/finance
    "ndtv.com": "lean left",                    # India – Progressive editorial stance
    "ara.cat": "lean left",                     # Spain – Catalan progressive daily
    "nnn.ng": "center",                         # Nigeria – News agency
    "varese7press.it": "center",                # Italy – Regional daily
    "varesenews.it": "center",                  # Italy – Regional daily
    "metropoles.com": "center",                 # Brazil – Mainstream portal
    "rionegro.com.ar": "center",                # Argentina – Regional daily
    "campusreview.com.au": "center",            # Australia – Education-focused
    "pitchfork.com": "lean left",               # US – Music/culture
    "kogiflame.com": "center",                  # Nigeria – Regional outlet
    "lanuevacronica.com": "center",             # Spain – Regional daily
    "lbccviking.com": "center",                 # US – Long Beach City College student paper
    "dailyreviewonline-ng.com": "center",       # Nigeria – Neutral
    "ynetnews.com": "lean left",                # Israel – English-language, progressive tone
    "salamanca24horas.com": "center",           # Spain – Regional daily
    "stkittsgazette.com": "center",             # St. Kitts – Neutral
    "wprost.pl": "lean right",                  # Poland – Conservative weekly
    "tagesschau.de": "center",                  # Germany – Public broadcaster
    "lagaceta.com.ar": "center",                # Argentina – Regional daily
    "oko.press": "lean left",                   # Poland – Investigative, progressive
    "dailytimesng.com": "center",               # Nigeria – Neutral
    "eldebate.com.ar": "center",                # Argentina – Regional daily
    "eltribuno.com": "center",                  # Argentina – Regional daily
    "adressa.no": "center",                     # Norway – Adresseavisen
    "tagblatt.ch": "center",                    # Switzerland – Regional daily
    "okay.ng": "center",                        # Nigeria – Neutral
    "stvincenttribune.com": "center",           # St. Vincent – Neutral
    "dominicagazette.com": "center",            # Dominica – Neutral
    "guyanainquirer.com": "center",             # Guyana – Neutral
    "grenadachronicle.com": "center",           # Grenada – Neutral
    "dominicanrepublicpost.com": "center",      # Dominican Republic – Neutral
    "haitigazette.com": "center",               # Haiti – Neutral
    "puertoricotribune.com": "center",           # Puerto Rico – Neutral
    "trinidadtribune.com": "center",          # Trinidad – neutral
    "jamaicainquirer.com": "center",          # Jamaica – neutral
    "bahamasspectator.com": "center",         # Bahamas – neutral
    "stluciachronicle.com": "center",         # St. Lucia – neutral
    "superdeporte.es": "center",              # Spain – sports daily
    "trybuna.info": "left",                   # Poland – socialist/leftist
    "indipendenteonline.it": "center",        # Italy – neutral
    "belami.rs": "center",                    # Serbia – neutral
    "abril.com.br": "center",                 # Brazil – mainstream magazine
    "vizionplus.tv": "center",                # Albania – mainstream TV
    "nowgrenada.com": "center",               # Grenada – neutral
    "dailykos.com": "left",                   # US – progressive blog
    "021.rs": "center",                       # Serbia – neutral
    "rtv.rs": "center",                       # Serbia – public broadcaster
    "lafm.com.co": "center",                  # Colombia – mainstream radio
    "inews.co.uk": "lean left",               # UK – digital outlet
    "zuonline.ch": "center",                  # Switzerland – finance
    "zsz.ch": "center",                       # Switzerland – regional
    "landbote.ch": "center",                  # Switzerland – regional
    "thunertagblatt.ch": "center",            # Switzerland – regional
    "weltexpress.info": "lean left",          # Germany – progressive commentary
    "kenyoncollegian.com": "center",          # US – student paper
    "seattlespectator.com": "center",         # US – Seattle Univ. student paper
    "pauljorion.com": "left",                 # France – progressive blog
    "brf.be": "center",                       # Belgium – regional
    "punchng.com": "center",                  # Nigeria – mainstream daily
    "the-sun.com": "lean right",              # US edition of The Sun
    "lanazione.it": "center",                 # Italy – mainstream daily
    "morningstaronline.co.uk": "left",        # UK – socialist daily
    "blikopnieuws.nl": "center",              # Netherlands – neutral
    "saz-aktuell.com": "center",              # Spain – neutral
    "pcccourier.com": "center",               # US – Pasadena student paper
    "jungewelt.de": "left",                   # Germany – socialist daily
    "20minutos.es": "center",                 # Spain – mainstream daily
    "lapresse.ca": "center",                  # Canada – mainstream daily
    "fordhamobserver.com": "center",          # US – Fordham Univ. student paper
    "gettysburgian.com": "center",            # US – Gettysburg College student paper
    "dailydot.com": "lean left",              # US – digital culture outlet
    "thestandard.com.hk": "center",           # Hong Kong – mainstream daily
    "catalunyadiari.com": "center",           # Spain – regional
    "monitorulexpres.ro": "center",           # Romania – regional
    "tuoitrenews.vn": "center",               # Vietnam – mainstream daily
    "daylightng.com": "center",               # Nigeria – neutral
    "politics.co.uk": "center",               # UK – commentary
    "sunstar.com.ph": "center",               # Philippines – mainstream daily
    "pinkvilla.com": "center",                # India – entertainment
    "zdf.de": "center",                       # Germany – public broadcaster
    "ilriformista.it": "lean left",           # Italy – progressive
    "ticotimes.net": "center",                # Costa Rica – English-language
    "diariocritico.com": "center",            # Spain – commentary
    "bernews.com": "center",                  # Bermuda – mainstream daily
    "guernseypress.com": "center",            # Guernsey – mainstream daily
    "jerseyeveningpost.com": "center",        # Jersey – mainstream daily
    "larepublica.co": "center",               # Colombia – mainstream daily
    "wired.jp": "lean left",                  # Japan – tech/culture
    "tion.ro": "center",                      # Romania – regional
    "thesun.co.uk": "lean right",             # UK – tabloid
    "nrk.no": "center",                       # Norway – public broadcaster
    "borneobulletin.com.bn": "center",        # Brunei – mainstream daily
    "lastampa.it": "lean left",               # Italy – progressive daily
    "polsatnews.pl": "lean right",            # Poland – conservative TV
    "trend.az": "center",                     # Azerbaijan – mainstream daily
    "elindependiente.com": "center",          # Spain – mainstream daily
    "eldia.com": "center",                    # Argentina – mainstream daily
    "technologyreview.jp": "center",          # Japan – MIT Tech Review local
    "republika.co.id": "lean right",          # Indonesia – conservative daily
    "neuquenalinstante.com.ar": "center",     # Argentina – regional
    "surinenglish.com": "center",             # Spain – expat daily
    "csudhbulletin.com": "center",            # US – CSU Dominguez Hills student paper
    "liberoquotidiano.it": "lean right",      # Italy – conservative daily
    "lagazzettadelmezzogiorno.it": "center",  # Italy – regional daily
    "gazeta.pl": "center",                    # Poland – mainstream portal
    "lestimes.com": "center",                 # Lesotho – mainstream daily
    "hallmarknews.com": "center",             # Nigeria – neutral
    "people.cn": "right",                     # China – state-run
    "36ng.ng": "center",                      # Nigeria – entertainment
    "valeursactuelles.com": "right",          # France – conservative weekly
    "ecodibergamo.it": "center",              # Italy – regional daily
    "lhrtimes.com": "center",                 # Pakistan – neutral
    "lalibre.be": "center",                   # Belgium – mainstream daily
    "thesimpsonian.com": "center",            # US – Simpson College student paper
    "thecrite.com": "center",                 # US – Univ. of Northern Colorado student paper
    "gwhatchet.com": "center",                # US – George Washington Univ. student paper
    "hs.fi": "center",                        # Finland – Helsingin Sanomat
    "rpdnoticias.com": "center",              # Argentina – regional
    "aoc.media": "lean left",                 # France – progressive commentary
    "sjuhawknews.com": "center",              # US – St. Joseph’s Univ. student paper
    "nd.nl": "center",                        # Netherlands – neutral
    "uatrav.com": "center",                   # US – Univ. of Arkansas student paper
    "la-croix.com": "lean left",              # France – Catholic progressive daily
    "socialsamosa.com": "center",             # India – marketing/tech
    "francetvinfo.fr": "center",              # France – public broadcaster
    "opencanada.org": "center",               # Canada – commentary
    "reinformation.tv": "right",              # France – far-right commentary
    "newsbusters.org": "right",               # US – conservative watchdog
    "berkeleybeacon.com": "center",           # US – Emerson College student paper
    "lanoticiadigital.com.ar": "center",      # Argentina – regional
    "kpakpandofm.com.ng": "center",           # Nigeria – radio
    "tvcnews.tv": "center",                   # Nigeria – mainstream TV
    "businessmirror.com.ph": "center",         # Philippines – mainstream daily
    "numerama.com": "lean left",             # France – tech/culture, progressive
    "naharnet.com": "center",                # Lebanon – English-language, neutral
    "thestkittsnevisobserver.com": "center", # St. Kitts – mainstream daily
    "ladige.it": "center",                   # Italy – regional daily
    "sueddeutsche.de": "lean left",          # Germany – Süddeutsche Zeitung, progressive
    "eldiario.es": "left",                   # Spain – progressive investigative
    "dailystatesman.com.gh": "lean right",   # Ghana – conservative
    "aargauerzeitung.ch": "center",          # Switzerland – regional daily
    "elmercurio.com.mx": "center",           # Mexico – regional daily
    "luzernerzeitung.ch": "center",          # Switzerland – regional daily
    "ariesonline.com.ar": "center",          # Argentina – regional
    "maravipost.com": "center",              # Malawi – neutral
    "viva.co.id": "center",                  # Indonesia – mainstream portal
    "lapatilla.com": "lean right",           # Venezuela – opposition, conservative
    "jurnal.md": "center",                   # Moldova – mainstream daily
    "expressen.se": "lean right",            # Sweden – tabloid, conservative
    "prlog.org": "center",                   # US – press release distributor
    "baylorlariat.com": "center",            # US – Baylor Univ. student paper
    "hotair.com": "right",                   # US – conservative commentary
    "vanderbilthustler.com": "center",       # US – Vanderbilt Univ. student paper
    "bellanaija.com": "center",              # Nigeria – lifestyle/entertainment
    "humanite.fr": "left",                   # France – communist daily
    "ziarulnational.md": "center",           # Moldova – mainstream daily
    "ghanaiantimes.com.gh": "center",        # Ghana – mainstream daily
    "cugetliber.ro": "center",               # Romania – regional daily
    "jhunewsletter.com": "center",           # US – Johns Hopkins Univ. student paper
    "byuiscroll.org": "center",              # US – BYU-Idaho student paper
    "libertatea.ro": "lean left",            # Romania – tabloid, progressive
    "mainecampus.com": "center",             # US – Univ. of Maine student paper
    "francesoir.fr": "lean right",           # France – conservative
    "letemps.ch": "lean left",               # Switzerland – progressive daily
    "ellitoral.com.ar": "center",            # Argentina – regional daily
    "herault-tribune.com": "center",         # France – regional daily
    "thaipost.net": "lean right",            # Thailand – conservative
    "diariosur.es": "center",                # Spain – regional daily
    "suedostschweiz.ch": "center",           # Switzerland – regional daily
    "one.com.mt": "center",                  # Malta – mainstream daily
    "kuenselonline.com": "center",           # Bhutan – national daily
    "indiasnews.net": "center",              # India – aggregator
    "nigeriannewsdirect.com": "center",      # Nigeria – mainstream daily
    "davidsonian.com": "center",             # US – Davidson College student paper
    "netsecurity.ne.jp": "center",           # Japan – tech/security
    "que.es": "center",                      # Spain – mainstream portal
    "ugandanews.net": "center",              # Uganda – aggregator
    "theuknews.com": "center",               # UK – aggregator
    "thetriangle.org": "center",             # US – Drexel Univ. student paper
    "elespanol.com": "lean right",           # Spain – conservative digital daily
    "britainnews.net": "center",             # UK – aggregator
    "unitedkingdomnews.net": "center",       # UK – aggregator
    "timescolonist.com": "center",           # Canada – regional daily
    "neusroom.com": "center",                # Nigeria – digital outlet
    "asiatoday.co.kr": "center",             # South Korea – mainstream daily
    "patriotpost.us": "right",               # US – conservative commentary
    "chinanews.net": "right",                # China – state-run
    "ctvnews.ca": "center",                  # Canada – mainstream broadcaster
    "beijingnews.net": "right",              # China – state-run
    "shanghainews.net": "right",             # China – state-run
    "ibtimes.com.au": "center",              # Australia – mainstream daily
    "romaniajournal.ro": "center",           # Romania – English-language
    "forbes.com.mx": "center",               # Mexico – business daily
    "thetech.com": "center",                 # US – MIT student paper
    "lyoncapitale.fr": "center",             # France – regional daily
    "excite.co.jp": "center",                # Japan – portal
    "polityka.pl": "lean left",              # Poland – progressive weekly
    "kimberleybulletin.com": "center",       # Canada – regional daily
    "abbynews.com": "center",                # Canada – regional daily
    "trailtimes.ca": "center",               # Canada – regional daily
    "heraldo.es": "center",                  # Spain – regional daily
    "amarujala.com": "center",               # India – mainstream Hindi daily
    "ign.com": "center",                     # US – gaming/entertainment
    "dailymaverick.co.za": "lean left",      # South Africa – investigative, progressive
    "abcnyheter.se": "center",               # Norway – mainstream daily
    "nationalmemo.com": "lean left",         # US – progressive commentary
    "sn.se": "center",                       # Sweden – regional daily
    "aap.com.au": "center",                  # Australia – news agency
    "kkuriren.se": "center",                 # Sweden – regional daily
    "vietnamplus.vn": "center",              # Vietnam – state-run, neutral tone
    "bizjournals.com": "center",             # US – business-focused
    "corriere.it": "center",                 # Italy – Corriere della Sera, centrist
    "gazette.al": "center",                  # Albania – mainstream daily
    "sciencesetavenir.fr": "center",         # France – science magazine
    "thelogicalindian.com": "lean left",     # India – progressive digital
    "jamaicaobserver.com": "center",         # Jamaica – mainstream daily
    "freitag.de": "left",                    # Germany – progressive weekly
    "business-standard.com": "center",       # India – business daily
    "danas.rs": "lean left",                 # Serbia – progressive daily
    "calgaryherald.com": "center",           # Canada – mainstream daily
    "news24.com": "center",                  # South Africa – mainstream daily
    "parade.com": "center",                  # US – entertainment/lifestyle
    "rtlnieuws.nl": "center",                # Netherlands – mainstream broadcaster
    "manoramaonline.com": "center",          # India – mainstream regional
    "citinewsroom.com": "center",            # Ghana – mainstream daily
    "yenimesaj.com.tr": "lean right",        # Turkey – conservative
    "amsterdamnews.net": "center",           # US – African-American focus
    "kbc.co.ke": "center",                   # Kenya – public broadcaster
    "cbc.bb": "center",                      # Barbados – mainstream daily
    "bizwatchnigeria.ng": "center",          # Nigeria – business daily
    "thestar.com.my": "center",              # Malaysia – mainstream daily
    "google.com": "center",                  # US – aggregator
    "haaretz.com": "lean left",               # Israel – progressive daily
    "usnews.com": "center",                  # US News & World Report – centrist, factual
    "bssnews.net": "center",                 # Bangladesh Sangbad Sangstha – state-run
    "gunosy.com": "center",                  # Japan – news aggregator
    "herald.ng": "center",                   # Nigeria – neutral
    "moneycontrol.com": "center",            # India – business/finance
    "wam.ae": "right",                       # UAE – state-run, pro-government
    "freemalaysiatoday.com": "lean left",    # Malaysia – independent, critical of govt
    "france24.com": "center",                # France – public broadcaster
    "thehimalayantimes.com": "center",       # Nepal – mainstream daily
    "themalaysianreserve.com": "center",     # Malaysia – business daily
    "msn.com": "lean left",                  # Aggregator, often carries liberal-leaning content
    "phnompenhpost.com": "center",           # Cambodia – mainstream daily
    "newbusinessethiopia.com": "center",     # Ethiopia – business news
    "pri.org": "lean left",                  # Public Radio International – progressive tone
    "infobae.com": "center",                 # Argentina – mainstream daily
    "bq-magazine.com": "center",             # Qatar – business magazine
    "marca.com": "center",                   # Spain – sports daily
    "firstpost.com": "center",               # India – mainstream portal
    "nationaljournal.com": "center",         # US – policy-focused, neutral
    "tribune-intl.com": "center",            # Australia – multicultural outlet
    "businesschief.com": "center",           # International business magazine
    "impress.co.jp": "center",               # Japan – tech/business
    "medium.com": "lean left",               # US – commentary platform, progressive tone
    "forbesindia.com": "center",             # India – business magazine
    "tunein.com": "center",                  # US – radio aggregator
    "laprovence.com": "center",              # France – regional daily
    "eluniversal.com.mx": "center",          # Mexico – mainstream daily
    "monitor.co.ug": "center",               # Uganda – mainstream daily
    "newsarawaktribune.com.my": "center",    # Malaysia – regional daily
    "theaggie.org": "center",                # UC Davis student paper
    "canadanews.net": "center",              # Aggregator
    "gulf-times.com": "center",              # Qatar – mainstream daily
    "gelocal.it": "center",                  # Italy – regional daily
    "thewire.in": "lean left",               # India – progressive investigative
    "thesandspur.org": "center",             # Rollins College student paper
    "quintopoder.com.co": "center",          # Colombia – regional daily
    "elcolombiano.com": "center",            # Colombia – mainstream daily
    "chronicle.gi": "center",                # Gibraltar – mainstream daily
    "limportant.fr": "center",               # France – aggregator
    "vov.vn": "center",                      # Vietnam – state-run
    "svt.se": "center",                      # Sweden – public broadcaster
    "pugetsound.edu": "center",              # US – university outlet
    "cadranpolitic.ro": "center",            # Romania – commentary
    "canadastandard.com": "center",          # Aggregator
    "scotsman.com": "center",                # Scotland – mainstream daily
    "sudouest.fr": "center",                 # France – regional daily
    "eurolibertes.com": "right",             # France – far-right commentary
    "singaporenews.net": "center",           # Aggregator
    "tdg.ch": "center",                      # Switzerland – Tribune de Genève
    "24heures.ch": "center",                 # Switzerland – regional daily
    "estadao.com.br": "center",              # Brazil – mainstream daily
    "bdnews24.com": "center",                # Bangladesh – mainstream daily
    "bnr.bg": "center",                      # Bulgaria – public broadcaster
    "anglicanjournal.com": "center",         # Canada – church publication
    "profil.at": "center",                   # Austria – mainstream magazine
    "rpi.edu": "center",                     # US – student outlet
    "lest-eclair.fr": "center",              # France – regional daily
    "lunion.fr": "center",                   # France – regional daily
    "thebutlercollegian.com": "center",      # US – Butler Univ. student paper
    "japantimes.co.jp": "center",            # Japan – English-language daily
    "thepeninsulaqatar.com": "center",       # Qatar – mainstream daily
    "armytimes.com": "center",               # US – military-focused
    "ghheadlines.com": "center",             # Ghana – aggregator
    "airforcetimes.com": "center",           # US – military-focused
    "navytimes.com": "center",               # US – military-focused
    "statehornet.com": "center",             # US – Sacramento State student paper
    "newzealandnews.net": "center",          # Aggregator
    "indonesianews.net": "center",           # Aggregator
    "jakartanews.net": "center",             # Aggregator
    "reporteindigo.com": "center",           # Mexico – investigative daily
    "ourtimebd.com": "center",               # Bangladesh – neutral
    "wiwo.de": "center",                     # Germany – Wirtschaftswoche, business
    "businessworld.in": "center",            # India – business daily
    "uproxx.com": "lean left",               # US – pop culture commentary
    "tiranatimes.com": "center",             # Albania – mainstream daily
    "groene.nl": "lean left",                # Netherlands – progressive weekly
    "nineoclock.ro": "center",               # Romania – English-language
    "realitatea.net": "center",              # Romania – mainstream daily
    "aydinses.com": "center",                # Turkey – regional
    "mndaily.com": "lean left",              # US – Univ. of Minnesota student paper
    "australianherald.com": "center",        # Aggregator
    "australiannews.net": "center",          # Aggregator
    "lepoint.fr": "lean right",              # France – conservative weekly
    "rtl.be": "center",                      # Belgium – mainstream broadcaster
    "thaipbs.or.th": "center",               # Thailand – public broadcaster
    "brytfmonline.com": "center",            # Ghana – neutral
    "ojim.fr": "right",                      # France – conservative media watchdog
    "hani.co.kr": "lean left",               # South Korea – progressive daily
    "fajar.co.id": "center",                 # Indonesia – mainstream daily
    "courrierinternational.com": "lean left",# France – international coverage
    "thesunflower.com": "center",            # US – Wichita State Univ. student paper
    "mbl.is": "center",                      # Iceland – mainstream daily
    "advancetitan.com": "center",            # US – Univ. of Wisconsin Oshkosh student paper
    "rttnews.com": "center",                 # US – business wire
    "unionesarda.it": "center",              # Italy – regional daily
    "thecostaricanews.com": "center",        # Costa Rica – English-language
    "tamilmurasu.com.sg": "center",          # Singapore – Tamil-language daily
    "afaqs.com": "center",                   # India – marketing/media
    "paz.de": "center",                      # Germany – regional
    "dailyeasternnews.com": "center",         # US – Eastern Illinois Univ. student paper
    "dataphyte.com": "center",              # Nigeria – data journalism, neutral
    "haberturk.com": "lean right",          # Turkey – pro-government leaning
    "mybroadband.co.za": "center",          # South Africa – tech/business
    "businesswire.com": "center",           # US – press release distributor
    "laprovinciadicomo.it": "center",       # Italy – regional daily
    "theeastafrican.co.ke": "center",       # Kenya – regional daily
    "philippinesnews.net": "center",        # Aggregator
    "taipeinews.net": "center",             # Aggregator
    "philippinetimes.com": "center",        # Aggregator
    "am990formosa.com": "center",           # Argentina – regional radio
    "mein-geld-medien.de": "center",        # Germany – finance/business
    "iol.co.za": "center",                  # South Africa – mainstream daily
    "opinionnigeria.com": "center",         # Nigeria – commentary
    "people.com.cn": "right",               # China – state-run
    "opednews.com": "lean left",            # US – progressive commentary
    "ottawacitizen.com": "center",          # Canada – mainstream daily
    "abidingtv.com": "center",              # Nigeria – Christian outlet
    "24-horas.mx": "center",                # Mexico – mainstream daily
    "newsletter.co.uk": "center",           # UK – aggregator
    "oradesibiu.ro": "center",              # Romania – regional daily
    "volksblatt.at": "center",              # Austria – regional daily
    "elclarinete.com.mx": "center",         # Mexico – regional daily
    "thoughtleader.co.za": "lean left",     # South Africa – commentary
    "gazzetta.it": "center",                # Italy – sports daily
    "lfpress.com": "center",                # Canada – London Free Press
    "rd.nl": "center",                      # Netherlands – Reformatorisch Dagblad, conservative Christian
    "theaimn.com": "lean left",             # Australia – progressive commentary
    "courrier.jp": "center",                # Japan – business/tech
    "flux.md": "center",                    # Moldova – mainstream daily
    "vlt.se": "center",                     # Sweden – regional daily
    "refinery29.com": "left",               # US – lifestyle/culture, progressive
    "huffingtonpost.co.uk": "lean left",    # UK – HuffPost, progressive
    "atlantico.fr": "lean right",           # France – conservative commentary
    "monitorfg.ro": "center",               # Romania – regional daily
    "unzensuriert.at": "right",             # Austria – far-right commentary
    "boerse-online.de": "center",           # Germany – finance/business
    "salzburg24.at": "center",              # Austria – regional daily
    "tribuneindia.com": "center",           # India – mainstream daily
    "oneindia.com": "center",               # India – mainstream portal
    "ilfriuli.it": "center",                # Italy – regional daily
    "italpress.com": "center",              # Italy – news agency
    "petra.gov.jo": "right",                # Jordan – state-run
    "mondo.rs": "center",                   # Serbia – mainstream daily
    "focustaiwan.tw": "center",             # Taiwan – CNA English service
    "shn.ch": "center",                     # Switzerland – regional daily
    "birminghammail.co.uk": "center",       # UK – regional daily
    "ismedia.jp": "center",                 # Japan – business/tech
    "samoanews.com": "center",              # Samoa – mainstream daily
    "canarias7.es": "center",               # Spain – regional daily
    "standard.rs": "center",                # Serbia – mainstream daily
    "opensecrets.org": "center",            # US – nonprofit watchdog
    "telemadrid.es": "center",              # Spain – regional broadcaster
    "trud.ru": "lean right",                # Russia – conservative daily
    "dispatchlive.co.za": "center",         # South Africa – mainstream daily
    "pmnewsnigeria.com": "center",          # Nigeria – mainstream daily
    "argentinastar.com": "center",          # Aggregator
    "buenosairesnews.net": "center",        # Aggregator
    "argentinanews.net": "center",          # Aggregator
    "ncronline.org": "lean left",           # US – National Catholic Reporter
    "ildispariquotidiano.it": "center",     # Italy – regional daily
    "americanfreepress.net": "right",   # US – conspiratorial, extremist
    "khaosod.co.th": "center",              # Thailand – mainstream daily
    "modernghana.com": "center",            # Ghana – mainstream daily
    "thelocal.se": "center",                # Sweden – English-language daily
    "cdns.com.tw": "center",                # Taiwan – regional daily
    "commentcamarche.net": "center",        # France – tech portal
    "ambito.com": "center",                 # Argentina – business daily
    "goldengatexpress.org": "center",       # US – San Francisco State Univ. student paper
    "sagat.no": "center",                   # Norway – regional daily
    "techable.jp": "center",                # Japan – tech/business
    "limburger.nl": "center",               # Netherlands – regional daily
    "lagazettedescommunes.com": "center",   # France – regional daily
    "elbistaninsesi.com": "center",         # Turkey – regional daily
    "cumhuriyet.com.tr": "lean left",       # Turkey – progressive daily
    "broadview.org": "lean left",           # Canada – progressive magazine
    "diariodeleon.es": "center",            # Spain – regional daily
    "lesoir.be": "lean left",               # Belgium – progressive daily
    "publico.es": "lean left",              # Spain – progressive daily
    "reddeeradvocate.com": "center",        # Canada – regional daily
    "jomhornews.com": "center",             # Iran – neutral
    "graphic.com.gh": "center",             # Ghana – mainstream daily
    "macleans.ca": "center",                # Canada – mainstream magazine
    "dohanews.co": "center",                # Qatar – independent daily
    "aktiv-online.de": "center",            # Germany – regional daily
    "dailymirror.lk": "center",             # Sri Lanka – mainstream daily
    "3-mob.com": "center",                  # Zimbabwe – neutral
    "efe.com": "center",                    # Spain – news agency
    "wallstreetitalia.com": "center",       # Italy – business daily
    "dagbladet.no": "lean left",            # Norway – progressive daily
    "20minutes.fr": "center",               # France – mainstream daily
    "troymedia.com": "center",              # Canada – commentary
    "handelsblatt.com": "center",           # Germany – business daily
    "elconfidencialdigital.com": "center",  # Spain – mainstream daily
    "thenewdaily.com.au": "lean left",      # Australia – progressive daily
    "smp.no": "center",                     # Norway – regional daily
    "ictnews.org": "center",                # Vietnam – tech/business
    "lavozdigital.es": "center",            # Spain – regional daily
    "boersen-zeitung.de": "center",         # Germany – finance daily
    "elcorreogallego.es": "center",         # Spain – regional daily
    "thephuketnews.com": "center",           # Thailand – regional daily
    "perfil.com": "center",                  # Argentina – mainstream daily
    "cshoy24.com.ar": "center",              # Argentina – regional outlet
    "pattayamail.com": "center",             # Thailand – local news
    "hbl.fi": "center",                      # Finland – Hufvudstadsbladet, centrist
    "aravot-en.am": "center",                # Armenia – mainstream daily
    "ekuriren.se": "center",                 # Sweden – Eskilstuna-Kuriren
    "moneyweb.co.za": "center",              # South Africa – business/finance
    "noticierouniversal.com": "center",      # Spain – aggregator
    "nu.nl": "center",                       # Netherlands – mainstream portal
    "wartaekonomi.co.id": "center",          # Indonesia – business/finance
    "thedepauw.com": "center",               # US – DePauw Univ. student paper
    "loyolamaroon.com": "center",            # US – Loyola Univ. student paper
    "ynaija.com": "lean left",               # Nigeria – progressive digital
    "parool.nl": "center",                   # Netherlands – mainstream daily
    "dailytarheel.com": "lean left",         # US – UNC student paper
    "liberation.fr": "left",                 # France – socialist daily
    "cbn.co.za": "center",                   # South Africa – Christian outlet
    "jungle.world": "left",                  # Germany – progressive weekly
    "vanguardngr.com": "center",             # Nigeria – mainstream daily
    "salamancartvaldia.es": "center",        # Spain – regional daily
    "kommunal-rapport.no": "center",         # Norway – municipal affairs
    "pulse.ng": "lean left",                 # Nigeria – lifestyle/news
    "dailynexus.com": "lean left",           # US – UC Santa Barbara student paper
    "ariananews.af": "center",               # Afghanistan – mainstream daily
    "chargerbulletin.com": "center",         # US – Univ. of New Haven student paper
    "iomtoday.co.im": "center",              # Isle of Man – mainstream daily
    "kommersant.ru": "lean right",           # Russia – pro-business conservative
    "observadorcentral.com.ar": "center",    # Argentina – regional outlet
    "rnanews.com": "center",                 # Nigeria – neutral
    "elimparcial.com": "center",             # Mexico – mainstream daily
    "rfi.fr": "center",                      # France – Radio France Internationale
    "worldtimes.co.jp": "center",            # Japan – mainstream daily
    "aristeguinoticias.com": "lean left",    # Mexico – investigative, progressive
    "alba24.ro": "center",                   # Romania – regional daily
    "tijd.be": "center",                     # Belgium – business daily
    "sydsvenskan.se": "lean left",           # Sweden – progressive daily
    "radiogdansk.pl": "center",              # Poland – regional broadcaster
    "linternaute.com": "center",             # France – portal
    "hd.se": "center",                       # Sweden – Helsingborgs Dagblad
    "zdnet.fr": "center",                    # France – tech/business
    "rtr.ch": "center",                      # Switzerland – regional broadcaster
    "lexo.al": "center",                     # Albania – neutral
    "nouvelobs.com": "lean left",            # France – progressive weekly
    "hln.be": "center",                      # Belgium – Het Laatste Nieuws
    "newsclick.in": "lean left",             # India – progressive digital
    "destentor.nl": "center",                # Netherlands – regional daily
    "bndestem.nl": "center",                 # Netherlands – regional daily
    "pzc.nl": "center",                      # Netherlands – regional daily
    "ad.nl": "center",                       # Netherlands – Algemeen Dagblad
    "ed.nl": "center",                       # Netherlands – Eindhovens Dagblad
    "bd.nl": "center",                       # Netherlands – Brabants Dagblad
    "tubantia.nl": "center",                 # Netherlands – Twentsche Courant
    "gelderlander.nl": "center",             # Netherlands – De Gelderlander
    "ndsmcobserver.com": "center",           # US – Notre Dame student paper
    "dbknews.com": "center",                 # US – Univ. of Maryland student paper
    "oregonlive.com": "lean left",           # US – Oregonian, progressive tone
    "capital.fr": "center",                  # France – business/finance
    "indiewire.com": "lean left",            # US – film/culture, progressive
    "nacion.com": "center",                  # Costa Rica – mainstream daily
    "milenio.com": "center",                 # Mexico – mainstream daily
    "radionigeria.gov.ng": "center",         # Nigeria – state-run
    "tuftsdaily.com": "center",              # US – Tufts Univ. student paper
    "bienpublic.com": "center",              # France – regional daily
    "lalsace.fr": "center",                  # France – regional daily
    "7sur7.be": "center",                    # Belgium – mainstream portal
    "tf1info.fr": "center",                  # France – mainstream broadcaster
    "dn.no": "center",                       # Norway – Dagens Næringsliv, business
    "nextinpact.com": "lean left",           # France – tech/policy, progressive
    "opindia.com": "right",                  # India – conservative digital
    "vozpopuli.com": "center",               # Spain – mainstream daily
    "thepanamanews.com": "lean left",        # Panama – progressive commentary
    "abante.com.ph": "center",               # Philippines – tabloid
    "remate.ph": "center",                   # Philippines – tabloid
    "eurweb.com": "lean left",               # US – African-American culture, progressive
    "herald.co.zw": "lean right",            # Zimbabwe – state-aligned
    "newsonair.com": "center",               # India – All India Radio
    "noticiasvigo.es": "center",             # Spain – regional daily
    "barcelonanews.net": "center",           # Aggregator
    "thesundaily.my": "center",              # Malaysia – mainstream daily
    "dailyuw.com": "center",                 # US – Univ. of Washington student paper
    "fijitimes.com": "center",               # Fiji – mainstream daily
    "nationalnewswatch.com": "lean left",    # Canada – progressive aggregator
    "brusselstimes.com": "center",           # Belgium – mainstream daily
    "demorgen.be": "lean left",              # Belgium – progressive daily
    "ledauphine.com": "center",              # France – regional daily
    "lejsl.com": "center",                   # France – regional daily
    "leprogres.fr": "center",                # France – regional daily
    "republicain-lorrain.fr": "center",      # France – regional daily
    "vosgesmatin.fr": "center",              # France – regional daily
    "estrepublicain.fr": "center",           # France – regional daily
    "kenyan-post.com": "lean right",         # Kenya – populist tabloid
    "misionesonline.net": "center",          # Argentina – regional daily
    "dziennikbaltycki.pl": "center",         # Poland – regional daily
    "naszemiasto.pl": "center",              # Poland – local portal
    "elsoldemexico.com.mx": "center",        # Mexico – mainstream daily
    "elbravo.mx": "center",                  # Mexico – regional daily
    "alahednews.com.lb": "right",            # Lebanon – Hezbollah-affiliated
    "radio.opole.pl": "center",              # Poland – regional broadcaster
    "gazetakrakowska.pl": "center",          # Poland – regional daily
    "kurierlubelski.pl": "center",            # Poland – regional daily
    # Poland – regional dailies, generally centrist
    "dzienniklodzki.pl": "center",
    "expressilustrowany.pl": "center",
    "nowiny24.pl": "center",
    "nowosci.com.pl": "center",
    "dziennikzachodni.pl": "center",
    "gazetalubuska.pl": "center",
    "pomorska.pl": "center",
    "gloswielkopolski.pl": "center",
    "wspolczesna.pl": "center",
    "poranny.pl": "center",
    "dziennikpolski24.pl": "center",
    "prachachat.net": "center",              # Thailand – business daily
    "usforacle.com": "center",               # Univ. of South Florida student paper
    "e-vid.ru": "right",                     # Russia – conservative outlet
    "spectatornews.com": "center",           # US – student paper
    "tv2.no": "center",                      # Norway – mainstream broadcaster
    "theabujainquirer.com": "center",        # Nigeria – neutral
    "echodnia.eu": "center",                 # Poland – regional daily
    "helsinkitimes.fi": "center",            # Finland – English-language daily
    "ewn.co.za": "center",                   # South Africa – Eyewitness News
    "volkskrant.nl": "lean left",            # Netherlands – progressive daily
    "allanyheter.com": "center",             # Sweden – aggregator
    "scrippsnews.com": "center",             # US – rated centrist by Ad Fontes
    "eikernytt.no": "center",                # Norway – regional
    "antiwar.com": "lean left",              # US – libertarian anti-war
    "thelocal.no": "center",                 # Norway – English-language daily
    "folha.com.br": "lean left",             # Brazil – Folha de S.Paulo
    "leblogalupus.com": "right",             # France – conservative blog
    "trouw.nl": "lean left",                 # Netherlands – progressive daily
    "latin-america.jp": "center",            # Japan – regional portal
    "lainformacion.com": "center",           # Spain – mainstream portal
    "plenglish.com": "lean left",            # Cuba – state-run English service
    "woz.ch": "center",                      # Switzerland – regional
    "bnr.nl": "center",                      # Netherlands – business radio
    "stripes.com": "center",                 # US – Stars and Stripes, military
    "lesechos.fr": "center",                 # France – business daily
    "rmol.co": "center",                     # Indonesia – mainstream portal
    "americanindependent.com": "lean left",  # US – progressive commentary
    "sfgate.com": "lean left",               # US – San Francisco Chronicle portal
    "gva.be": "center",                      # Belgium – Gazet van Antwerpen
    "hbvl.be": "center",                     # Belgium – Het Belang van Limburg
    "thefridaytimes.com": "lean left",       # Pakistan – progressive weekly
    "abclive.in": "center",                  # India – neutral
    "iotnews.jp": "center",                  # Japan – tech/business
    "vocedimantova.it": "center",            # Italy – regional daily
    "tvazteca.com": "center",                # Mexico – mainstream broadcaster
    "leparisien.fr": "center",               # France – mainstream daily
    "heraldlive.co.za": "center",            # South Africa – regional daily
    "theweek.co.uk": "center",               # UK – centrist magazine
    "bestnaira.com": "center",               # Nigeria – aggregator
    "tempo.co": "center",                    # Indonesia – mainstream daily
    "eyeradio.org": "center",                # South Sudan – neutral
    "nbr.co.nz": "center",                   # New Zealand – business daily
    "pakistannews.net": "center",            # Aggregator
    "dhnet.be": "center",                    # Belgium – mainstream daily
    "ilgiornaledivicenza.it": "center",      # Italy – regional daily
    "bresciaoggi.it": "center",              # Italy – regional daily
    "huffingtonpost.fr": "lean left",        # France – progressive
    "nieuws.nl": "center",                   # Netherlands – portal
    "ledevoir.com": "lean left",             # Canada – progressive daily
    "notretemps.com": "center",              # France – lifestyle
    "interfax.ru": "right",                  # Russia – state-aligned
    "rsi.ch": "center",                      # Switzerland – public broadcaster
    "top-channel.tv": "center",              # Albania – mainstream broadcaster
    "metronews.it": "center",                # Italy – portal
    "omni.se": "center",                     # Sweden – portal
    "radio-canada.ca": "lean left",          # Canada – public broadcaster
    "publimetro.com.mx": "center",           # Mexico – mainstream daily
    "elimparcial.es": "center",              # Spain – regional daily
    "journaldemontreal.com": "lean right",   # Canada – populist tabloid
    "liderweb.mx": "center",                 # Mexico – regional daily
    "sinembargo.mx": "lean left",            # Mexico – investigative, progressive
    "closeup.mx": "lean left",               # Mexico – SinEmbargo vertical
    "ucol.mx": "center",                     # Mexico – university outlet
    "diario.mx": "center",                   # Mexico – mainstream daily
    "sipse.com": "center",                   # Mexico – regional daily
    "enfoqueinformativo.mx": "center",       # Mexico – regional daily
    "nigerianobservernews.com": "center",    # Nigeria – mainstream daily
    "eldiariodechihuahua.mx": "center",      # Mexico – regional daily
    "lavozdemichoacan.com.mx": "center",     # Mexico – regional daily
    "urgente24.com": "lean right",           # Argentina – conservative portal
    "elwaha-dz.com": "center",               # Algeria – regional outlet
    "journaldequebec.com": "lean right",     # Canada – populist tabloid
    "proceso.com.mx": "lean left",           # Mexico – investigative, progressive
    "inform.kz": "center",                   # Kazakhstan – state-run
    "tempi.it": "right",                     # Italy – Catholic conservative
    "geo.fr": "center",                      # France – lifestyle
    "diario16.com": "lean left",             # Spain – progressive
    "diariosanrafael.com.ar": "center",      # Argentina – regional daily
    "capetalk.co.za": "center",              # South Africa – talk radio
    "topalbaniaradio.com": "center",         # Albania – mainstream radio
    "vanguardia.com.mx": "center",           # Mexico – mainstream daily
    "sopitas.com": "lean left",              # Mexico – progressive digital
    "iltalehti.fi": "center",                # Finland – mainstream tabloid
    "chinanews.com": "right",                # China – state-run
    "sie7edechiapas.com": "center",          # Mexico – regional daily
    "plazadearmas.com.mx": "center",         # Mexico – regional daily
    "radiokontakt.al": "center",             # Albania – mainstream radio
    "livedoor.com": "center",                # Japan – portal
    "lebanon24.com": "center",                # Lebanon – mainstream dai
    "bisnis.com": "center",                  # Indonesia – business/finance
    "dna.fr": "center",                      # France – mainstream daily
    "mundopoliticodiario.com": "center",     # Spain – regional politics
    "srad.jp": "center",                     # Japan – tech/aggregator
    "jawapos.com": "center",                 # Indonesia – mainstream daily
    "brasil247.com": "lean left",            # Brazil – progressive digital
    "taiwandaily.net": "center",             # Taiwan – neutral
    "cnews.fr": "lean right",                # France – conservative TV
    "nna-leb.gov.lb": "right",               # Lebanon – state-run
    "channel4.com": "lean left",             # UK – Channel 4 News, progressive
    "falkopingstidning.se": "center",        # Sweden – regional daily
    "skaraborgslanstidning.se": "center",    # Sweden – regional daily
    "skovdenyheter.se": "center",            # Sweden – regional daily
    "vimmerbytidning.se": "center",          # Sweden – regional daily
    "vt.se": "center",                       # Sweden – Västerviks Tidningen
    "nwt.se": "center",                      # Sweden – Nya Wermlands-Tidningen
    "gd.se": "center",                       # Sweden – Gefle Dagblad
    "sverigesradio.se": "center",            # Sweden – public broadcaster
    "yohaig.ng": "center",                   # Nigeria – aggregator
    "arbetarbladet.se": "lean left",         # Sweden – progressive daily
    "l1.nl": "center",                       # Netherlands – regional broadcaster
    "voiceofnaija.ng": "center",             # Nigeria – neutral
    "wienerzeitung.at": "center",            # Austria – mainstream daily
    "tv4.se": "center",                      # Sweden – mainstream broadcaster
    "thelocal.fr": "center",                 # France – English-language daily
    "europe1.fr": "lean right",              # France – conservative radio
    "sudinfo.be": "center",                  # Belgium – mainstream daily
    "francebleu.fr": "center",               # France – public radio
    "hket.com": "center",                    # Hong Kong Economic Times
    "yam.md": "center",                      # Moldova – aggregator
    "cicero.de": "lean right",               # Germany – conservative magazine
    "moldova.org": "center",                 # Moldova – independent outlet
    "barrons.com": "center",                 # US – business/finance
    "cameroononline.org": "center",          # Cameroon – neutral
    "themonthly.com.au": "lean left",        # Australia – progressive magazine
    "dvhn.nl": "center",                     # Netherlands – Dagblad van het Noorden
    "forbesjapan.com": "center",             # Japan – business/finance
    "beobachter.ch": "center",               # Switzerland – consumer magazine
    "giornaledibrescia.it": "center",        # Italy – regional daily
    "weeklycuttingedge.com": "lean right",   # Pakistan – conservative commentary
    "elmundofinanciero.com": "center",       # Spain – business/finance
    "newsday.com.ng": "center",              # Nigeria – neutral
    "meridiano.mx": "center",                # Mexico – sports daily
    "vertigopolitico.com": "center",         # Mexico – politics
    "seychellesnewsagency.com": "center",    # Seychelles – state-run
    "portafolio.co": "center",               # Colombia – business daily
    "konbini.com": "lean left",              # France – youth/culture, progressive
    "eldiario.com.co": "center",             # Colombia – mainstream daily
    "jornada.com.mx": "lean left",           # Mexico – progressive daily
    "eleconomista.com.ar": "center",         # Argentina – business daily
    "liputan6.com": "center",                # Indonesia – mainstream portal
    "elintransigente.com": "center",         # Argentina – digital daily
    "yourgibraltartv.com": "center",         # Gibraltar – local TV
    "imparcialoaxaca.mx": "center",          # Mexico – regional daily
    "varldenidag.se": "lean right",          # Sweden – Christian conservative
    "askanews.it": "center",                 # Italy – news agency
    "chacoprensa.com": "center",             # Argentina – regional daily
    "slate.fr": "lean left",                 # France – progressive commentary
    "indiantelevision.com": "center",        # India – industry outlet
    "ilrestodelcarlino.it": "center",        # Italy – mainstream daily
    "slobodnaevropa.org": "lean left",       # Balkans – RFE/RL service
    "rabble.ca": "left",                     # Canada – progressive indie media
    "ladepeche.fr": "center",                # France – regional daily
    "astaga.com": "center",                  # Indonesia – portal
    "glasamerike.net": "center",             # VOA Balkans – neutral
    "kuwaitbulletin.com": "center",          # Kuwait – neutral
    "khmertimeskh.com": "center",            # Cambodia – mainstream daily
    "kentwired.com": "center",               # US – Kent State Univ. student paper
    "nyheter24.se": "lean left",             # Sweden – progressive digital
    "bignewsnetwork.com": "center",          # Aggregator
    "sunnewsonline.com": "lean right",       # Nigeria – conservative
    "kaieteurnewsonline.com": "center",      # Guyana – mainstream daily
    "mwnation.com": "center",                # Malawi – mainstream daily
    "bt.se": "center",                       # Sweden – Borås Tidning
    "nexojornal.com.br": "lean left",        # Brazil – progressive digital
    "aftenposten.no": "center",              # Norway – mainstream daily
    "thehilltoponline.com": "center",        # US – Howard Univ. student paper
    "guadanews.es": "center",                # Spain – regional daily
    "depauliaonline.com": "center",          # US – DePaul Univ. student paper
    "rebelnews.ie": "right",                 # Ireland – conservative commentary
    "telam.com.ar": "lean left",             # Argentina – state-run, Peronist
    "thedailyguardian.net": "center",        # Philippines – mainstream daily
    "newswirengr.com": "center",             # Nigeria – neutral
    "themiamihurricane.com": "center",       # US – Univ. of Miami student paper
    "postcourier.com.pg": "center",          # Papua New Guinea – mainstream daily
    "nationalaccordnewspaper.com": "center", # Nigeria – neutral
    "catamarcaprovincia.com.ar": "center",   # Argentina – regional daily
    "laverdad.es": "center",                 # Spain – regional daily
    "elnortedecastilla.es": "center",        # Spain – regional daily
    "lasprovincias.es": "center",            # Spain – regional daily
    "elcomercio.es": "center",               # Spain – regional daily
    "leonoticias.com": "center",             # Spain – regional daily
    "hoy.es": "center",                      # Spain – regional daily
    "eldiariomontanes.es": "center",         # Spain – regional daily
    "larioja.com": "center",                 # Spain – regional daily
    "telerama.fr": "center",                 # France – regional daily
    "maraviexpress.com": "center",           # Malawi – neutral
    "burgosconecta.es": "center",            # Spain – regional daily
    "nyasatimes.com": "lean left",           # Malawi – progressive digital
    "gazeta.ru": "lean right",                # Russia – conservative daily
    "avantionline.it": "center",             # Italy – mainstream daily
    "extra.com.co": "center",                # Colombia – mainstream daily
    "diariodelcauca.com.co": "center",       # Colombia – regional daily
    "elpais.cr": "center",                   # Costa Rica – mainstream daily
    "arcturius.org": "lean left",            # France – progressive commentary
    "etownian.com": "center",                # US – Elizabethtown College student paper
    "thelocal.de": "center",                 # Germany – English-language daily
    "kualalumpurnews.net": "center",         # Malaysia – aggregator
    "nigeriasun.com": "center",              # Nigeria – aggregator
    "cambodiantimes.com": "center",          # Cambodia – aggregator
    "afghanistansun.com": "center",          # Afghanistan – aggregator
    "novosti.rs": "lean right",              # Serbia – conservative daily
    "eriepa.com": "center",                  # US – regional outlet
    "canadianbusiness.com": "center",        # Canada – business magazine
    "suara.com": "center",                   # Indonesia – mainstream portal
    "nicematin.com": "center",               # France – regional daily
    "varmatin.com": "center",                # France – regional daily
    "hellomagazine.com": "center",           # UK – entertainment/lifestyle
    "thecarletonian.com": "center",          # US – Carleton College student paper
    "volanteonline.com": "center",           # US – Univ. of South Dakota student paper
    "digiday.jp": "center",                  # Japan – business/tech, neutral
    "nifty.com": "center",                   # Japan – portal
    "thairath.co.th": "center",              # Thailand – mainstream daily
    "cndigital.com.ar": "center",            # Argentina – regional outlet
    "wyborcza.pl": "lean left",              # Poland – Gazeta Wyborcza, progressive
    "laloyolan.com": "center",               # US – Loyola Marymount Univ. student paper
    "lobosnews.com.ar": "center",            # Argentina – regional outlet
    "lapoliticaonline.com": "lean left",     # Argentina – progressive political site
    "aip.nu": "center",                      # Sweden – regional outlet
    "gnnliberia.com": "center",              # Liberia – mainstream daily
    "24matins.fr": "center",                 # France – mainstream portal
    "milliyet.com.tr": "lean right",         # Turkey – conservative daily
    "thecambodianews.net": "center",         # Cambodia – aggregator
    "naslovi.net": "center",                 
    "elnacional.cat": "lean left"            
}


In [ ]:
# Assume bias_map is already defined as a Python dictionary

# Create a cleaned version
cleaned_bias_map = {
    domain: (
        orientation.replace("lean left", "lean-left")
                   .replace("lean right", "lean-right")
    )
    for domain, orientation in bias_map.items()
}

# If you want to overwrite the original:
bias_map = cleaned_bias_map


In [ ]:
#extract domain from the 'media_url' column
df["domain"] = df["media_url"].str.extract(r"(?:https?:\/\/)?(?:www\.)?([^\/]+)")


In [7]:
def bias_lookup(domain):
    return bias_map.get(domain, "unknown")

df["political_orientation"] = df["domain"].map(bias_lookup)


### Results: Political Orientation Distribution

The following section shows the counts of each orientation in our dataset.  
This distribution highlights whether the dataset is balanced or skewed toward certain perspectives.

In [ ]:
#the distribution of political orientation
print("Political Orientation Distribution:")
print(df["political_orientation"].value_counts())

#ehe total number of outlets analyzed
print("\nTotal outlets analyzed:", len(df))

Political Orientation Distribution:
center        23271
lean-left      8214
lean-right     1515
right          1285
left           1114
Name: political_orientation, dtype: int64

Total outlets analyzed: 35399


In [9]:
missing_domains = df.loc[~df["domain"].isin(bias_map.keys()), "domain"].unique()
print("Missing domains:", missing_domains[:100])


Missing domains: []


### **Result Summary:** 
The dataset is dominated by outlets classified as **center (23,271 entries)**, with a much smaller share **lean-left (8,214)**, and very few **left (1,114)** or **right (1,285)**. **Lean-right** is also relatively **small (1,515)**. This means your collection is heavily weighted toward **centrist or neutral** sources.

---

### Interpretation
- **Balance:** The dataset is not evenly distributed. About **70%+ are “center”**, which may reflect the fact that many regional, business, or wire-service outlets are coded as neutral.
- **Asymmetry:** There are **more lean-left outlets than lean-right** (8,214 vs. 1,515). This could be due to the inclusion of many European and Latin American sources, where progressive editorial lines are more common.
- **Extremes are rare:** Both “left” and “right” categories are small, showing that strongly partisan outlets are underrepresented compared to centrist or mildly leaning ones.

---

### Reference
Media bias classification is often based on projects like **[AllSides Media Bias Ratings](https://www.allsides.com/media-bias/media-bias-ratings)**, **[Ad Fontes Media](https://app.adfontesmedia.com/chart/interactive)**, and **[Ground News](https://ground.news/bias-bar)**, which categorize outlets into *left, lean-left, center, lean-right, right* based on editorial stance, language, and ownership.  
For example, AllSides explains that:
- *Center* outlets “do not predictably favor either side of the political spectrum.”  
- *Lean-left* or *lean-right* outlets show consistent but mild bias in story selection or framing.  
- *Left* and *Right* outlets show strong ideological framing and selective coverage.  

---


For domains that is not listed in these reference sites, we used **Gemini/GenAI** to query the missing domain directly. The model provided the political orientation (center, lean-left, left, lean-right, right) so that every domain in the dataset could be classified consistently.
